### ISSUE TITLE
extend Lib

### ISSUE THREAD

**Issue by mbta009** [ayushsharma82/ESP-DASH#10]
Thanks for a great library.
I want to extend your lib and add other items like form, chart, button and .... Can you guide me where to start? And what can I do? For example, the items that you have in EasyUI are added to this lib.
Thanks. 
Mahdi Barati

**Comment by ayushsharma82** [comment]
Hi, 
The Library works on JSON Input.
[Check Here](https://github.com/ayushsharma82/ESP-DASH/blob/master/src/EspDash.cpp#L108)

So You can add custom JSON Elements and then modify frontend javascript (using zepto.js) to render components based on the data provided by JSON Response.

**Comment by mbta009** [comment]
Hello and respect
Thanks for the reply. I have done some research on jQuery, zeptojs. The first question is which editor you use to edit the HTML source code. For debugging and testing, do files need to be uploaded and tested on ESP every time? In Windows I created a json file manually and placed it beside the HTML file.
{wifiStatus: 1, wifiSSID: mbta, usedHeap: 63%, userTab: [{tab tab: Visitors, tabValue: 259}]}
The open HTML page in the Windows Browser locally shows only the logo image and the color change of the background. What is your solution for testing in the Windows environment?
Many thanks to you.

**Comment by mbta009** [comment]
The second question is why there is a Tab 15 restriction for the dashboard? Is it possible to increase this number? 
Thanks.
