### ISSUE TITLE
Values Stored as Global Variable

### ISSUE THREAD

**Issue by HackEduca** [ayushsharma82/ESP-DASH#100]
Hello, First of all, congratulation to your amazing work.
This is the best dashboard I´ve seen so far.

I would like to check with you if is there a way to keep the values as a global variable to be used outside the callback.
In your Example: "Interactive.ino", I woulk like to use the value (I replaced by x) as a variable to be used in a delay function:

Example:
`  /* Attach Slider Callback */
  slider.attachCallback([&](int x){
    /* Print our new slider value received from dashboard */
    Serial.println("Slider Triggered: "+String(x));
    /* Make sure we update our slider's value and send update to dashboard */
    slider.update(x);
    dashboard.sendUpdates();
  });`

So, when I try to use like this:

` delay ( x * 1000);
      Serial.println("X: " + x);`

I receive this error message:
```
exit status 1
'x' was not declared in this scope
```

I can imagine that this is caused due to a scope of variable, but is there any way to make all variable global?

Thanks

**Comment by polaco1782** [comment]
the value comes from a lambda function which passes it as a reference. It is visible under its scope.

you're trying to implicit sum with " " and x. You need to cast it as arduino string type.

Serial.println("X: " + String(x));

**Comment by ayushsharma82** [comment]
As mentioned by @polaco1782 , You can access that `x` variable inside the callback function only.
