### ISSUE TITLE
card slider to RGB color setting

### ISSUE THREAD

**Issue by Artkool** [ayushsharma82/ESP-DASH#101]
hi how can i apply the three  #slider tabs to RGB color setting

**Comment by Artkool** [comment]
Hi, I found a solution to my problem, it was enough to use arrays with 3 elements, the code is below, maybe someone will use it
Card kolorR(&dashboard, SLIDER_CARD, "color R", "", 0, 255);
Card kolorG(&dashboard, SLIDER_CARD, "color G", "", 0, 255);
Card kolorB(&dashboard, SLIDER_CARD, "color B", "", 0, 255);

int YAxis[] = {R, G, B };

void setup() 
{
  colorR.attachCallback([&](int R)
  {
    colorR.update(R);
    YAxis[0] = (R);
    chart1.updateY(YAxis, 3);
    dashboard.sendUpdates();
    pixels.setPixelColor(7, pixels.Color(YAxis[0], YAxis[1], YAxis[2]));
    pixels.show();
  });

  kolorG.attachCallback([&](int G)
  {
    colorG.update(G);
    YAxis[1] = (G);
    chart1.updateY(YAxis, 3);
    dashboard.sendUpdates();
    pixels.setPixelColor(7, pixels.Color(YAxis[0], YAxis[1], YAxis[2]));
    pixels.show();
  });

  kolorB.attachCallback([&](int B)
  {
    colorB.update(B);
    YAxis[2] = (B);
    chart1.updateY(YAxis, 3);
    dashboard.sendUpdates();
    pixels.setPixelColor(7, pixels.Color(YAxis[0], YAxis[1], YAxis[2]));
    pixels.show();
  });

  delay (2000);
}

**Comment by ayushsharma82** [comment]
I'm glad that you tried & fixed the problem by yourself. Thanks for your contribution!
