### ISSUE TITLE
Error: Could not decode a text frame as UTF-8

### ISSUE THREAD

**Issue by mbta009** [ayushsharma82/ESP-DASH#103]
Hi.
To use Generic Cards for String values in the console execution dashboard, the following error appears. There is no problem with some String values. Of course, this problem at first I thought was a problem with the number of characters, but it is not.
Error: Could not decode a text frame as UTF-8 arduino websocket
for example :
"12345678" No problem
"123456789" error appears.
this console error is a common problem in web sockets

in addition Can someone show me example how to use String for generic card.
Should c_str() be used for dynamic string?

**Comment by ayushsharma82** [comment]
Thanks for reporting this bug. I'll update this thread when it's fixed. Thanks!

**Comment by ayushsharma82** [comment]
Fixed with #105
