### ISSUE TITLE
are there anywere some PICTURES that show how the dashboard will look like?

### ISSUE THREAD

**Issue by StefanL38** [ayushsharma82/ESP-DASH#111]
The headline says it all:
are there anywere some **PICTURES** that show how the dashboard will look like?

Getting started by separating the code into multiple parts? and that's all?

Put yourself into the position of somebody who ist totally new to ESP-dash.
Just knowing in general what a dashboard is. Nothing more.

Having some pictures and the correspnding code that creates THIS kind of dashboard would be very helpful

I will spend $25 if you can provide a fully pictured manual

**Comment by ayushsharma82** [comment]
@StefanL38 Did you see the main photo in the readme? That has almost every component. Better than that, I would suggest you go through the various examples provided in the repo. Running the code is better than viewing pictures right?


Disclaimer: It's an open-source project for people by the people. If you think there are fewer images, you can spin up an example provided with the repo and screenshot the cards and add them to the documentation here: https://github.com/ayushsharma82/ESP-DASH/tree/gh-pages/src

**Comment by StefanL38** [comment]
Hi Ayush,
OK I tried some of the example-code and they worked.
Though a very important point I'm missing is to pre-program the order of the cards.

If you want your ESP-DASH-library to become famous you have to add this feature. 
Can you tell a date or a month when placing the cards in a user-defined order will be implemented?
best regards Stefan

**Comment by ayushsharma82** [comment]
Hi Stefan,
I appreciate your concerns and suggestions.
To be honest, ESP-DASH was started as a personal project and I don't really see any point in putting so much work into an open-source project if it's not earning you daily bread. All the changes you see in this project were done when I was free or bored or to fix some bugs.

There is no timeline for now but people are invited to invest their free time to implement the features they want.

**Comment by StefanL38** [comment]
OK the initial question is answered. I close the issue
