### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by DanielGtellols** [ayushsharma82/ESP-DASH#112]
First of all thank you very much for your work!

I am having problems with the progress bar chart. The bar graph always marks full with any value, except the zero value, which works well and is shown empty. In other words, the graphic bar does not match the value.

Card rsoc(&dashboard, PROGRESS_CARD,"CARGA BATERIA", "%", 0, bateria);

Void loop(){
rsoc.update(bateria);
…….
}

![8169A2B4-559E-4159-8D24-EB2957266325](https://user-images.githubusercontent.com/81962547/113582676-f51b5700-9628-11eb-8bf1-6a953e456ea5.jpeg)

And finally, is there any way to add a title or modify the existing one?

Thank you very much for everything, your work is fantastic.

**Comment by ayushsharma82** [comment]
Problem is here: `Card rsoc(&dashboard, PROGRESS_CARD,"CARGA BATERIA", "%", 0, bateria);`

Correct:  `Card rsoc(&dashboard, PROGRESS_CARD,"CARGA BATERIA", "%", 0, 100);` 

The last parameter of this function should be the maximum 'expected' value. Consider those parameters as the start of the progress bar and the end of it. So, any value passed to the `update` function between that range will show correctly.

Let me know if this fixes your issue.

**Comment by ayushsharma82** [comment]
@DanielGtellols  Just checked. Apart from the syntax, there is a bug in the webpage as well. I'll update you with a fix in a couple of minutes.

**Comment by DanielGtellols** [comment]
It hasn't worked. I keep getting the same error. The bar is not updated. Thanks for your help

**Comment by ayushsharma82** [comment]
Fixed with 849523e

Please download the master branch to reflect the changes. Thanks for reporting the issue.

**Comment by ayushsharma82** [comment]
Please feel free to close the issue if it was resolved.

Thanks

**Comment by DanielGtellols** [comment]
Works correctly! Thanks
