### ISSUE TITLE
Questions about how ESP-DASH works

### ISSUE THREAD

**Issue by StefanL38** [ayushsharma82/ESP-DASH#115]
Hi Ayush,

I started to analyse the sourcecode of the ESP-DASH-library.
I want to add the userdefined-card-order-feature to estimate the effort to do so
I need some help from you to answer some questions.

Do I understand right that the JSON-library does the details to generate the HTML-code that is sent to the requesting clients?

Inside the sourcecode-file ESPDash.cpp there some lines
`  // Generate JSON for all Cards
  for (int i=0; i < cards.Size(); i++) {
    Card *p = cards[i];
    cardsData += generateComponentJSON(p);
    cardsData += ",";
  }
`
is this the place where - inside of generateComponentJSON() - the HTML-code is generated?

So as this for-loop iterates through all cards: would this be a suitable place to add a index-number to change the sequence in which the cards will be placed on the website?

Or would a place inside of generateComponentJSON()  be more suitable?

For implementing a indexNumber that determines the sequence how the cards show up
different concepts are thinkable. 

1. Adding a new variable "IndexNr"   or   "ListPosNr"  inside the definition of structure card
2. An extra array that holds the pointers of the cards and some additional functions that assign the pointers to the cards 
and then iterate through this array 
Example: 
after 
`Card* humidity    = new Card(&MyDashboard, HUMIDITY_CARD, "Humidity", "%");
Card* temperature = new Card(&MyDashboard, TEMPERATURE_CARD, "Temperature", "°C");
Card* temperature2 = new Card(&MyDashboard, TEMPERATURE_CARD, "Temperature2", "°C");
`
the sequence inside cards[] itself is (just using example numbers to explain the principle)
cards[0] = 0xA000; // humidity
cards[1] = 0xB000; // temperature
cards[2] = 0xC000; // temperature2

Now an additional array gets the pointers to the cards assigned in a different order

CardOrder[0] = cards[2]; // temperature2
CardOrder[1] = cards[0]; // humidity
CardOrder[0] = cards[1]; // temperature

and calling the generateComponentJSON()-function is changed to
`  // Generate JSON for all Cards
  for (int i=0; i < cards.Size(); i++) {
    Card *p = CardOrder[i] //cards[i];
    cardsData += generateComponentJSON(p);
    cardsData += ",";
  }
`
would this work? 
or is the order in which the cards get generated distinguished somewhere else?

If somewhere else where?

best regards Stefan

**Comment by ayushsharma82** [comment]
The order of cards is not dependent on the order of items in the card array.

It's the Vuejs part that loops through the cards according to the type of it. [Reference](https://github.com/ayushsharma82/ESP-DASH/blob/master/vue-frontend/src/views/Home.vue#L5)

A single `index` (uint8) attribute should be sufficient in the C++ library, the rest of the work needs to be done in the Vuejs. It will require a bit of re-write in the 'reference' which I have provided above.

**Comment by StefanL38** [comment]
Hello Ayush,
thank you ver ymuch for pointing me to the right place.
I started to learn some javascript and did a quick crossreading about Vue.  It seems that the Vue-framework adds new commands like "v-for"  but I'm not sure.

I have added a new variable const int index in the cards.h / cards.cpp constructor. But I have no idea how I do access this variable in Vue.


the vue template like it is now does
`<generic-card v-for="card in getParticularCards('generic')" :key="card.id" :card="card"></generic-card>`

Would iterating through mean to re-write this statement or would it mean to add "index" somehow to the statement?

The template just mentions card.id. Is this  really the right place to add the index-attribute?

Lin 5 to 11 of home.vue iterates through the cards by type.

Do I  understand right that the method getParticularCards  puts the card into the array with the command
`cards.push(card);`
?

Your original constructor looks like this:
Card::Card(ESPDash *dachboard,  const int type, const char* name, const char* symbol, const int min, const int max) } 

`Card::Card(ESPDash *dachboard,  const int type, const char* name, const char* symbol, const int min, const int max) } 
`

If I added a parameter in the C++ code a new parameter "index"
File Card.cpp
Card::Card(ESPDash *dachboard, **const int index**, const int type, const char* name, const char* symbol, const int min, const int max) } 

`Card::Card(ESPDash *dachboard, const int index, const int type, const char* name, const char* symbol, const int min, const int max) } 
`

That then I can access parameter index in the vue-code with

 if(card.index === nextIndex){
          cards.push(card);
        }

and that then the cards will appear on the website in an order that is determined by index?

best regards Stefan

**Comment by ayushsharma82** [comment]
@StefanL38 , Simply adding index attribute in the constructor will not do it. It will require multiple edits in the whole source code ( JSON generation part, then editing the vue structure and changing card reactivity ). If it was that simple, I would have already done it in 10 minutes.

**Comment by StefanL38** [comment]
Hi Ayush,

OK I undertand. I'm taking my way through the code.
Is it right that in file Home-vue 
the methods getParticularCards and getParticularCharts
iterate through all cards by the type of the card?

`    getParticularCards(type) {
      let cards = [];
      for(let card of this.cards){
        if(**card.type** === type){
          cards.push(card);
        }
      }
      return cards;
`
This method returns an array 

The if-condition uses a value **card.type**
is the value of  **card.type**   stored in the card-structure of the Cpp-code or in some card-structure of the Vue-code?

Does this mean that inside file Home.vue I would have to write two methods
getCardsByIndex      getChartsByIndex

`    getCardsByIndex(index) {
      let cards = [];
      for(let card of this.cards){
        if(card.index === index){
          cards.push(card);
        }
      }
      return cards;
`


hm ... --- ... the codelines 1 to 11 in Home.vue
`<template>
  <div>
    <div class="container" v-if="cards.length > 0 || charts.length > 0">
      <div class="columns is-mobile is-multiline">
        <generic-card v-for="card in getParticularCards('generic')" :key="card.id" :card="card"></generic-card>
        <temperature-card v-for="card in getParticularCards('temperature')" :key="card.id" :card="card"></temperature-card>
        <humdidity-card v-for="card in getParticularCards('humidity')" :key="card.id" :card="card"></humdidity-card>
        <status-card v-for="card in getParticularCards('status')" :key="card.id" :card="card"></status-card>
        <progress-card v-for="card in getParticularCards('progress')" :key="card.id" :card="card"></progress-card>
        <slider-card v-for="card in getParticularCards('slider')" :key="card.id" :card="card"></slider-card>
        <button-card v-for="card in getParticularCards('button')" :key="card.id" :card="card"></button-card>
`

is using a v-for  loop for every card-type. This seems to be the difficult part.
Iterating through all cards by an index is different. 
What is not clear to me yet is:

In file Home.vue  Line 1 to 11 does this iterating create the sequence of the cards how they appear on the website?

This line looks like if it is creating HTML-code
`        <slider-card v-for="card in getParticularCards('slider')" :key="card.id" :card="card"></slider-card>
`
The code for all cards of type slider.  Is this correct?

If Yes this would mean to change the code here to something that
iterates through all cards by index  look-up card-type and depending on the card-type 

"templating"
<generic-card key="card.id" :card="card"></generic-card>
<button-card key="card.id" :card="card"></button-card>
<slider-card key="card.id" :card="card"></slider-card>

?
best regards Stefan

**Comment by StefanL38** [comment]
a completely different aproach would be to just throw out the gzipping.
Then the returned string to the Cpp-Code could be re-analysed inside the Cpp-code
and the order of the HTML-code could be re-arranged by an index.
Not very beautiful/elegant but doable.

The "lightning-fast"  will be gone. But of what use is a "lightning-fast" library where I can ### **_not_** define the order of the Website-GUI-elements?
best regards Stefan

**Comment by ayushsharma82** [comment]
@StefanL38 , I was going to release ESP-DASH **Pro** with a couple of new cards and charts, but after your issue, I took a day off and add this feature to it ( that required a complete rewrite of some vuejs files ).

If you anybody is interested in having custom order of cards ( indexing ) then do checkout ESP-DASH Pro.
**Available Here:** https://espdash.pro

**Comment by ayushsharma82** [comment]
ESP-DASH Docs ( https://ayushsharma82.github.io/ESP-DASH/ ) has been updated with images and now it contains a guide for both ESP-DASH Lite and ESP-DASH **Pro**.
