### ISSUE TITLE
removing zip-encding

### ISSUE THREAD

**Issue by StefanL38** [ayushsharma82/ESP-DASH#116]
Hello,

what do I have to change to remove the ZIP-compressing?

Some users on Arduino.cc think ZIP-compressed content could be malisious.
So a version that sends all html as unzipped text would create more trust into the library.

best regards Stefan

**Comment by ayushsharma82** [comment]
You can't, there is a reason for gzipping all of this. The actual size of webpage is around 1.4MB ( Unzipping it will blow past the 1MB limit of your firmware ( FLASH ) and possibly overflow your MCU's SRAM )

ESP-DASH has come a long way ( 4 years of work ) from using SPIFFS for the webpage to integrating everything into the firmware itself ( to make updating easier ).

I hope you understand, this is for user accessibility only. ESP8266 & ESP32 are not full fledge PCs. As this is out of the scope of the current nature of the library, I'm closing this issue.
