### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by puhycz** [ayushsharma82/ESP-DASH#117]
Hello, I buy ESP Dash Pro today. 

Upload to platformio workspace lib directory and change #include <ESPDash.h> to #include <ESPDashPro.h>. What next is need?

But it shows error:

lib\ESP-DASH-Pro-4.0.4\src/Card.h:61:10: note: candidate: void Card::attachCallback(std::function<void(const char*)>)
     void attachCallback(std::function<void(const char*)> cb);
          ^
src\main.cpp:614:27: error: call of overloaded 'attachCallback(setup()::<lambda(bool)>)' is ambiguous
                          });

Code here:

button4.attachCallback([&](bool value)
                         {
                           /* Print our new button value received from dashboard */
                           Serial.println("Button Triggered: " + String((value) ? "true" : "false"));
                           /* Make sure we update our button's value and send update to dashboard */
                           button4.update(value);
                           digitalWrite(ledPinRed, value);
                           dashboard.sendUpdates();
                         **});**

Same code with lite ESP Dash is ok. Please help me.

Thx,

Jan

**Comment by ayushsharma82** [comment]
Hi @puhycz ,

Thanks for your purchase.

With ESP-DASH Pro, the callback parameter was changed from `bool` to `int`. You can replace the callback line with `attachCallback([&](int value)`

Regards,
Ayush

**Comment by puhycz** [comment]
Thanks, but there is still some problem:

.pio\build\nodemcu-32s\libf06\libESP-DASH-Pro-4.0.4.a(Card.cpp.o): In function `Card::Card(ESPDash*, int, char const*, char const*, int, int)':
c:\.platformio\packages\toolchain-xtensa32@2.50200.97\xtensa-esp32-elf\include\c++\5.2.0\bits/move.h:188: multiple definition of `Card::Card(ESPDash*, int, char const*, char const*, int, int)'
.pio\build\nodemcu-32s\lib632\libESP-DASH.a(Card.cpp.o):C:\Users\puhy_1\Documents\Prace\Moje_projekty\ovladac_ventilu_zalevani\ESP32_ovladani_ventilu_zalevani/.pio\libdeps\nodemcu-32s\ESP-DASH\src/Card.cpp:6: first defined here
.pio\build\nodemcu-32s\libf06\libESP-DASH-Pro-4.0.4.a(Card.cpp.o): In function `Card::Card(ESPDash*, int, char const*, char const*, int, int)':
Card.cpp:(.text._ZN4CardC2EP7ESPDashiPKcS3_ii+0x0): multiple definition of `Card::Card(ESPDash*, int, char const*, char const*, int, int)'
.pio\build\nodemcu-32s\lib632\libESP-DASH.a(Card.cpp.o):Card.cpp:(.text._ZN4CardC2EP7ESPDashiPKcS3_ii+0x0): first defined here
.pio\build\nodemcu-32s\libf06\libESP-DASH-Pro-4.0.4.a(Card.cpp.o): In function `Card::update(int, char const*)':
Card.cpp:(.text._ZN4Card6updateEiPKc+0x0): multiple definition of `Card::update(int, char const*)'
.pio\build\nodemcu-32s\lib632\libESP-DASH.a(Card.cpp.o):Card.cpp:(.text._ZN4Card6updateEiPKc+0x0): first defined here
.pio\build\nodemcu-32s\libf06\libESP-DASH-Pro-4.0.4.a(Card.cpp.o): In function `Card::update(int)':
Card.cpp:(.text._ZN4Card6updateEi+0x0): multiple definition of `Card::update(int)'
.pio\build\nodemcu-32s\lib632\libESP-DASH.a(Card.cpp.o):Card.cpp:(.text._ZN4Card6updateEi+0x0): first defined here
.pio\build\nodemcu-32s\libf06\libESP-DASH-Pro-4.0.4.a(Card.cpp.o): In function `Card::update(float, char const*)':
Card.cpp:(.text._ZN4Card6updateEfPKc+0x0): multiple definition of `Card::update(float, char const*)'
.pio\build\nodemcu-32s\lib632\libESP-DASH.a(Card.cpp.o):Card.cpp:(.text._ZN4Card6updateEfPKc+0x0): first defined here
.pio\build\nodemcu-32s\libf06\libESP-DASH-Pro-4.0.4.a(Card.cpp.o): In function `Card::update(float)':
Card.cpp:(.text._ZN4Card6updateEf+0x0): multiple definition of `Card::update(float)'
.pio\build\nodemcu-32s\lib632\libESP-DASH.a(Card.cpp.o):Card.cpp:(.text._ZN4Card6updateEf+0x0): first defined here
.pio\build\nodemcu-32s\libf06\libESP-DASH-Pro-4.0.4.a(Card.cpp.o): In function `Card::update(char const*, char const*)':
Card.cpp:(.text._ZN4Card6updateEPKcS1_+0x0): multiple definition of `Card::update(char const*, char const*)'
.pio\build\nodemcu-32s\lib632\libESP-DASH.a(Card.cpp.o):Card.cpp:(.text._ZN4Card6updateEPKcS1_+0x0): first defined here
.pio\build\nodemcu-32s\libf06\libESP-DASH-Pro-4.0.4.a(Card.cpp.o): In function `Card::update(String const&, char const*)':
Card.cpp:(.text._ZN4Card6updateERK6StringPKc+0x0): multiple definition of `Card::update(String const&, char const*)'
.pio\build\nodemcu-32s\lib632\libESP-DASH.a(Card.cpp.o):Card.cpp:(.text._ZN4Card6updateERK6StringPKc+0x0): first defined here
.pio\build\nodemcu-32s\libf06\libESP-DASH-Pro-4.0.4.a(Card.cpp.o): In function `Card::update(char const*)':
Card.cpp:(.text._ZN4Card6updateEPKc+0x0): multiple definition of `Card::update(char const*)'
.pio\build\nodemcu-32s\lib632\libESP-DASH.a(Card.cpp.o):Card.cpp:(.text._ZN4Card6updateEPKc+0x0): first defined here
.pio\build\nodemcu-32s\libf06\libESP-DASH-Pro-4.0.4.a(Card.cpp.o): In function `Card::update(String const&)':
Card.cpp:(.text._ZN4Card6updateERK6String+0x0): multiple definition of `Card::update(String const&)'
.pio\build\nodemcu-32s\lib632\libESP-DASH.a(Card.cpp.o):Card.cpp:(.text._ZN4Card6updateERK6String+0x0): first defined here
.pio\build\nodemcu-32s\libf06\libESP-DASH-Pro-4.0.4.a(Card.cpp.o): In function `Card::update(bool, char const*)':
Card.cpp:(.text._ZN4Card6updateEbPKc+0x0): multiple definition of `Card::update(bool, char const*)'
.pio\build\nodemcu-32s\lib632\libESP-DASH.a(Card.cpp.o):Card.cpp:(.text._ZN4Card6updateEbPKc+0x0): first defined here
.pio\build\nodemcu-32s\libf06\libESP-DASH-Pro-4.0.4.a(Card.cpp.o): In function `Card::update(bool)':
Card.cpp:(.text._ZN4Card6updateEb+0x0): multiple definition of `Card::update(bool)'
.pio\build\nodemcu-32s\lib632\libESP-DASH.a(Card.cpp.o):Card.cpp:(.text._ZN4Card6updateEb+0x0): first defined here
.pio\build\nodemcu-32s\libf06\libESP-DASH-Pro-4.0.4.a(Card.cpp.o): In function `Card::~Card()':
Card.cpp:(.text._ZN4CardD2Ev+0x0): multiple definition of `Card::~Card()'
.pio\build\nodemcu-32s\lib632\libESP-DASH.a(Card.cpp.o):Card.cpp:(.text._ZN4CardD2Ev+0x0): first defined here
.pio\build\nodemcu-32s\libf06\libESP-DASH-Pro-4.0.4.a(Card.cpp.o): In function `Card::~Card()':
Card.cpp:(.text._ZN4CardD2Ev+0x0): multiple definition of `Card::~Card()'
.pio\build\nodemcu-32s\lib632\libESP-DASH.a(Card.cpp.o):Card.cpp:(.text._ZN4CardD2Ev+0x0): first defined here
.pio\build\nodemcu-32s\libf06\libESP-DASH-Pro-4.0.4.a(Card.cpp.o): In function `Card::attachCallback(std::function<void (int)>)':
Card.cpp:(.text._ZN4Card14attachCallbackESt8functionIFviEE+0x0): multiple definition of `Card::attachCallback(std::function<void (int)>)'
.pio\build\nodemcu-32s\lib632\libESP-DASH.a(Card.cpp.o):Card.cpp:(.text._ZN4Card14attachCallbackESt8functionIFviEE+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\nodemcu-32s\firmware.elf] Error 1

**Comment by ayushsharma82** [comment]
Please email me the code at ***@***.*** for debugging. You can also
send a short example which reproduces the problem.

Regards,
Ayush

**Comment by ayushsharma82** [comment]
Did you remove the ‘lite’ ESP-DASH from sketch? (  Remove this line:
#include <ESPDash.h> And keep #include of pro version )

**Comment by puhycz** [comment]
Yes, of course. There is only #include <ESPDashPro.h>. I send email with code now. Thx.

**Comment by ayushsharma82** [comment]
Compiled successfully on my PC. It is probably the build-cache issue, the compiler is still including lite ESPDash in your case. 
Try copying the code to a different project and then compile.

![image](https://user-images.githubusercontent.com/26592968/128138965-187b3424-cc64-4258-84b7-94a270c0a479.png)

**Comment by puhycz** [comment]
Ok, thanx, it works now. (After restarting VSCode + Platformio). I have
some next questions, sorry :-)

1) But I have one more problem with Android devices. Tested Samsung Galaxy
S4 and some Xiaomi. I have ESP32 with dash pro on IP (f.e. 192.168.10.195)
and on android devices in Chrome, when I type this IP, it very often
returns ERR_CONNECTION_RESET. On desktop PC is ok. And it on the same wifi.
From android, this IP is pingable. Are there some magic trick of settings
android chrome or dash webserver?

2) and how long is normal booting time for ESP dash? IP of ESP32 is
pingable immediately after reset, but ESP dash page is available after 30 -
40 sec. Is it normal?

3) is possible change image dashPro on the header of ESP Dash Pro page?

Thx,

Jan


st 4. 8. 2021 v 9:24 odesílatel Ayush Sharma ***@***.***>
napsal:

**Comment by ayushsharma82** [comment]
1) Please check if browsers in those phones support gzipped content. Dash webpage is gzip compressed.
2) Booting time is instant. You need to call `server.begin();` after WiFi is connected.
3) You can by compiling the Vuejs webpage source given in `vue-frontend` folder. You will require some experience with Nodejs. ( SVG logo is in Navbar.vue )

**Comment by ayushsharma82** [comment]
@puhycz One more tip: Make sure nothing is blocking in the code. If there is any delay or for function which takes too long to execute, it will slow the performance of AsyncWebServer.

**Comment by puhycz** [comment]
Ok, I try control it.

But

slider.setIndex(1);
temperature.setIndex(0);

Not function for me. It is possible dynamically change setIndex? Not
funcion in my case, object are not ordered.

slider.setIndex(1);
    temperature.setIndex(0);
    signalCard.update(WiFi.RSSI());
    cpuCard.update((int)getCpuFrequencyMhz());
    inputCard1.update(input1);
    inputCard2.update(surface);
    inputCard3.update(alarmIn);
    temperature.update(tempC);
    dashboard.sendUpdates();

[image: image.png]


st 4. 8. 2021 v 13:02 odesílatel Ayush Sharma ***@***.***>
napsal:

**Comment by ayushsharma82** [comment]
@puhycz  Please check if the cards update their order after page refresh?

**Comment by ayushsharma82** [comment]
@puhycz  I'll check on my ESP32 in a couple of hours and let you know the outcome.

**Comment by puhycz** [comment]
Cool, thanks!



st 4. 8. 2021 v 13:53 odesílatel Ayush Sharma ***@***.***>
napsal:

**Comment by ayushsharma82** [comment]
I think the error listed above was resolved within our conversation over email? If so, you may close this issue.

**Comment by puhycz** [comment]
Yes, thank you! It was fixed.
