### ISSUE TITLE
Port for ESP32

### ISSUE THREAD

**Issue by Craftplorer** [ayushsharma82/ESP-DASH#12]
Any plans to do a port for the esp32?
Would you think a minimal change port would be best or a complete rewrite?
For example EspDash.loop(); could be put into a task on the esp32.

**Comment by ayushsharma82** [comment]
Hi, 
I am working on 'V2' of ESP-DASH and that would be rewritten to work with Websockets. I will try my best to make it compatible with both ESP8266 and ESP32. 

Some newer things which i plan to add are:
- Websockets Communication
- Graphs
- Buttons
- Realtime Tabs

Keep Looking over this Repo for ESP-DASH V2. I will keep this issue open till ESP32 support is added.

**Comment by ayushsharma82** [comment]
I am excited to tell that ESP-DASH V2 has been released. Arduino Library manager will be have it's database updated with Version 2 by tomorrow. You can try to install it manually till then. Thanks!

**Comment by ayushsharma82** [comment]
and yeah, ESP32 support is added in V2. 😊🎉
