### ISSUE TITLE
Button Card not compiling[BUG]

### ISSUE THREAD

**Issue by TristanLund** [ayushsharma82/ESP-DASH#122]
If you try to use the button card as described in the documentation you will get an error.

This is because in card.cpp there is no reference to Card::attachCallback accepting a bool as an argument.

This is screenshot of the documentation.
![error1](https://user-images.githubusercontent.com/93341319/142635293-2a3646d8-fe30-4312-8250-446b18fc472c.PNG)

This is a screenshot of all of the attach callback references in Card.cpp
![error2](https://user-images.githubusercontent.com/93341319/142635370-b88d2d94-807e-4b62-8601-c46e2df0e077.PNG)

I was able to come up with a work around, and I can use the button card.

**Comment by ayushsharma82** [comment]
Hi @TristanLund ,

Thanks for reporting that! The callback function was changed from `bool` to `int` for accommodating additional cards. I'll update the documentation.

**Comment by ayushsharma82** [comment]
Fixed with V4 release and also updated documentation to use `int` rather than `bool`. [Reference](https://docs.espdash.pro/cards/button/#callback)
