### ISSUE TITLE
[BUG] the slider does not update correctly

### ISSUE THREAD

**Issue by zapikp** [ayushsharma82/ESP-DASH#124]
I have this code:

Card jas_den(&dashboard, SLIDER_CARD, "Jas den", "", 0, 1023);

jas_den.attachCallback([&](uint16_t value){
    if (value > intenzita_noc){
      intenzita_den = value;
      jas_den.update(value);
      dashboard.sendUpdates();
    } else {
      jas_den.update(intenzita_den);
      dashboard.sendUpdates();
    }
});
And I set  intenzita_den smaller then  intenzita_noc, card jas_den does not update corectly - I can see value set by hand and I can see yellow dot in right corner.

Is it bug?

![image](https://user-images.githubusercontent.com/56720963/145514928-a7daddd7-2b96-4c20-b1ae-e2d4de5d938f.png)

**Comment by ayushsharma82** [comment]
@zapikp , Does this also happen with the latest version? If possible please try it and report back.
