### ISSUE TITLE
2 errors  xTaskCreateUniversal and class EspClass' has no member named 'getSketchMD5'

### ISSUE THREAD

**Issue by rrsilver** [ayushsharma82/ESP-DASH#125]
I have a project and I want to read the temperature of a ds18b20 sensor and show it on the phone using esp-dash but when I went to compile it I got an error "AsyncTCP.cpp:221:141: error: 'xTaskCreateUniversal' was not declared in this scope
         xTaskCreateUniversal(_async_service_task, "async_tcp", 8192 * 2, NULL, 3, &_async_service_task_handle, CONFIG_ASYNC_TCP_RUNNING_CORE); ai on the advice of a user here I changed this code to xTaskCreatePinnedToCore(_async_service_task, "async_tcp", 8192 * 2, NULL, 3, &_async_service_task_handle, CONFIG_ASYNC_TCP_RUNNING_CORE);
oh it passed but stopped at this error
ESPDash.cpp: In member function 'String ESPDash::generateLayoutJSON(bool)':
ESPDash.cpp:203:40: error: 'class EspClass' has no member named 'getSketchMD5'
     stats += "\"sketchHash\":\"" + ESP.getSketchMD5() + "\",";
I really wanted to use esp-dash to make a presentation but I can't compile and record it in esp, my library version is 1.0.6 I've already looked at all these settings, thanks for all possible help, forgive my english google is my teacher

**Comment by ayushsharma82** [comment]
Closing as stale. If you still need help, you may open the issue again.
