### ISSUE TITLE
Climate card

### ISSUE THREAD

**Issue by hjkoster400d** [ayushsharma82/ESP-DASH#129]
Hi there,

Nice project and thanks for sharing with us.

Did you considered creating a climate card? That would be a nice component to add.

Let me know,
Grtz Rik

**Comment by ayushsharma82** [comment]
Thanks for suggestion. Added in [backlog](https://github.com/users/ayushsharma82/projects/2/views/1).

Backlog will be cleared as new releases roll out.

Regards,
Ayush Sharma
