### ISSUE TITLE
Can't install the package of Vue

### ISSUE THREAD

**Issue by fadelaryap** [ayushsharma82/ESP-DASH#132]
I couldn't install with npm install, it said that baseUrl is not allowed

**Comment by ayushsharma82** [comment]
Hi @fadelaryap , ESP-DASH V3 was created with VueJS 2 quite some years ago, I'm afraid it won't even compile now as Vue 3 has just been released and focus of community packages has also been shifted to support that new framework.

I suggest looking into the new ESP-DASH V4 release. The Pro version now offers a lot of customization without even touching the webpage code. Learn more [here](https://espdash.pro)
