### ISSUE TITLE
Dashboard public?

### ISSUE THREAD

**Issue by Rotzbua** [ayushsharma82/ESP-DASH#137]
Will the dashboard become public?
https://github.com/ayushsharma82/espdash-portal/

**Comment by ayushsharma82** [comment]
This time I've no intention to make the webpage public for the open-source version. The webpage source code will only be included with the pro version.

Contributors like you can still ask for it on my mail, I'll be happy to provide webpage source code to people who improve stuff for everyone. 🍻

**Comment by Rotzbua** [comment]
Thanks for the appreciation. 👍 
I recommend to remove the git submodule as it is private and thus the checkout fails for users. Also it would be useful to mention in the README that it is not published to avoid further reports.

**Comment by ayushsharma82** [comment]
Didn't think submodule would cause any issue as those have to be initialized manually? I'll remove it if you have faced any errors from git.
