### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cadot-eu** [ayushsharma82/ESP-DASH#138]
**Describe the bug**
In the page of the website [page of statistic]( https://docs.espdash.pro/custom-statistics/) , for add statistic, the method is
`stat1.set("Value 123");` but the good method is `stat1.set("Statistic 1",Value 123");` for the example.

**Comment by ayushsharma82** [comment]
Thanks for reporting. Fixed with https://github.com/ayushsharma82/ESP-DASH/commit/52868e6573e78c00bf7ffc9d5b27681e7260b360 .
