### ISSUE TITLE
add step for slider

### ISSUE THREAD

**Issue by cadot-eu** [ayushsharma82/ESP-DASH#139]
**Is your feature request related to a problem? Please describe.**
i want step for slider for facilty second division

**Describe the solution you'd like**
add in method slider step variable

**Comment by ayushsharma82** [comment]
Thanks for the suggestion. I've added it in [backlog](https://github.com/users/ayushsharma82/projects/2/views/1).

Backlog will be cleared as new releases are rolled out.

Regards,
Ayush Sharma

**Comment by cadot-eu** [comment]
thanks ;-)
