### ISSUE TITLE
Multiple selection card.

### ISSUE THREAD

**Issue by daarig** [ayushsharma82/ESP-DASH#140]
In my silly little project ( a wifi room thermostat) i will integrate a timer/scheduler-type function. I was thinking at a card that allows multiple selection like, think activating or deactivating the timer for 5 days in a row.. so a card with 7 or 2 or 5  (don't know how they'll fit on a phone screen but they'll definitely fit on a pc monitor) checkboxes-type buttons or maybe miniature buttons with names on top or just initials for small screens. Thanks for reading! Great project!

**Comment by ayushsharma82** [comment]
Do you mean a dropdown?

Example:
![image](https://user-images.githubusercontent.com/26592968/205467642-66a12753-9820-4a82-bca2-b812a30754a8.png)

**Comment by daarig** [comment]
No, something like a BUTTON_CARD but with 7 smaller buttons on the same card. I say 7 because in my sketch i need 7 but the "user" should be able to choose the needed amount, obviously the multiple button card can't bee too big.  

I made now i TAB with the ON and OFF time and another TAB with 7 cards for the 7 days of the week. My idea is that the TAB could be "moved" almost entirely into 1 BUTTON_CARD.


![Screenshot_20221203-005720.png](https://user-images.githubusercontent.com/74381438/205468472-fa4d384f-b463-4c44-bf76-1839cb9442d5.png)

Here you can see the "GIORNI" Tab. (It's DAYS in Italian...) So i placed 7 BUTTON_CARDS so that the final user can select on which day of the week the conditioner will be on or off. 
The 7 card on my phone occupies 7 rows, on a PC screen will take up a row and a half.

I think reducing tabs to a certain minimal is more efficient. 


But, on the other hand, a drop-down selector could work. I'm thinking relatively to my need...:

Drop-down:
1st selection=1-7
2nd selection=1-5
3rd selection=6-7

It could work. Even if, take this example... I'm at home 3 days of the week on smart-working.. Monday, Tuesday and Friday. I would like to turn on the air conditioning only on those days. 

But anyway this is just to give ideas. It's not to critic. 


Great work!

**Comment by ayushsharma82** [comment]
I get it. I've added it in backlog.
