### ISSUE TITLE
Change grafical items for the cards.

### ISSUE THREAD

**Issue by daarig** [ayushsharma82/ESP-DASH#141]
Change grafical items for the cards. Like think "Sonic" blu-ish buttons for my son's room, or pink-ish buttons daughter's room.... Or maybe this can allready be done in some manner that i don't know? Thank you!

**Comment by ayushsharma82** [comment]
Hi @daarig ,

This can be done by editing the webpage and compiling it again. I cannot possibly add this 'dynamic' functionality through Arduino library as that would decrease the performance of library by a lot. We are already running on bleeding edge. :)
