### ISSUE TITLE
Different and less "visible ""Connected" info small print

### ISSUE THREAD

**Issue by daarig** [ayushsharma82/ESP-DASH#142]
The "Connected" info small print on phones get's in the way, my opinion is that it should be placed on the bottom of the  screen, and make it maibe, some sort of an icon, or a "chain"-type link, or maiba an antenna pointing up.. or 2 point connected by a line that gets an "x" when connection failes. Thank again for reading!
![WhatsApp Image 2022-11-18 at 22 54 26](https://user-images.githubusercontent.com/74381438/202810986-927c5c4c-5602-426e-9951-3a019df36143.jpeg)

**Comment by ayushsharma82** [comment]
Hi @daarig ,

Logo on mobile navbar and padding above 'connected' tab has been fixed with v4.1.1 of ESP-DASH Pro.

I'll look towards your suggestion of moving the connected tab somewhere else for future releases

Regards,
Ayush Sharma
