### ISSUE TITLE
Button Card Callback expects boolean in demo app but int in the purchased app

### ISSUE THREAD

**Issue by jdannymo** [ayushsharma82/ESP-DASH#144]
I tried the demo option and wrote my code according. The button card callback function expects a boolean. After I purchased the full version my code did not compile. The problem is that the callback function for the button card expects an int. No big deal, but I wanted to let you know.

**Comment by ayushsharma82** [comment]
@jdannymo  This should be fixed with V4. Let me know if it still occurs on this release.
