### ISSUE TITLE
Drop list card

### ISSUE THREAD

**Issue by jdannymo** [ayushsharma82/ESP-DASH#145]
I would love to have a drop-list card. I like your library, and I would like more cards.

**Comment by ayushsharma82** [comment]
Thanks for the suggestion, I'll add it in my Todo list for new features.


___Disclaimer:___
All new cards & features are added to DASH Pro only. Open-source version of ESP-DASH is in long term support mode which will receive UI overhauls and bug fixes.

**Comment by ayushsharma82** [comment]
Added in [backlog](https://github.com/users/ayushsharma82/projects/2).
