### ISSUE TITLE
[BUG] Updating content and color on the Button Card when open on different windows.

### ISSUE THREAD

**Issue by jdannymo** [ayushsharma82/ESP-DASH#146]
When I click on a button card in one window, the color of the card is not updated in other windows. The card's status changes from "x" to "checkmark" or "checkmark" to "x," but the color stays the same.

**Comment by ayushsharma82** [comment]
Hi @jdannymo ,

This should be fixed with [v4.0.1](https://github.com/ayushsharma82/ESP-DASH/releases/tag/v4.0.1) release. Let me know after testing if you still face it.

Regards,
Ayush Sharma
