### ISSUE TITLE
[BUG] Multiple Connections to same esp32 dasboard. 

### ISSUE THREAD

**Issue by daarig** [ayushsharma82/ESP-DASH#147]
Hi again, this time it's serious... please correct me if i'm wrong or doing something in a bad way.
I can't connect wit PC and phone on the same time, or rather not with both PC and phone browsers working on the ESP page. 
Is it normal? 

Thanks for reading!

**Comment by ayushsharma82** [comment]
Hi @daarig ,

Can you tell us about which MCU you are using with ESP-DASH?

**Comment by daarig** [comment]
Hey, i'm using this one :https://it.aliexpress.com/item/1005004245157276.html?spm=a2g0o.productlist.main.11.5483cf1daK6K1O&algo_pvid=03e91e48-ab1f-4ebe-b123-2fe6e90c6a6d&algo_exp_id=03e91e48-ab1f-4ebe-b123-2fe6e90c6a6d-5&pdp_ext_f=%7B%22sku_id%22%3A%2212000028507441979%22%7D&pdp_npi=2%40dis%21EUR%2115.95%2111.32%21%21%21%21%21%402100b88516701115430464649d0749%2112000028507441979%21sea&curPageLogUid=xoDux0FhQEMa

**Comment by ayushsharma82** [comment]
Hey @daarig ,

I see it is an ESP32. From what I know, It should handle ESP-DASH pretty well. I've tested ESP-DASH on at least 4 active clients with every card & chart on the dashboard with ESP32.

I suggest running the ESP-DASH benchmark example on your microcontroller first to rule out any mistake in your code. If that example is running fine across all your devices then it's possible that your custom code which you run along side ESP-DASH has to be optimized. Sometimes user code takes up a lot of resources on ESP32 which can have adverse effects on the webserver performance.

**Comment by daarig** [comment]
I'll try as soon as possible. Thank you!

**Comment by ayushsharma82** [comment]
No issues! That's very common in this hobby. I'm glad your figured out the issue.
