### ISSUE TITLE
Develop WebPage 

### ISSUE THREAD

**Issue by mbta009** [ayushsharma82/ESP-DASH#15]
Hello and Regards, Thank you for your support
I would like to advise you on changes to the webpage and develop that, for example adding a tab and a new item, and .... What is framwork? I worked on ESPdash V1 and I could apply changes to my Jquery code, but in ESP Dash V2 it's a bit confusing to me. Thanks for introducing a step-by-step strategy.

**Comment by ayushsharma82** [comment]
ESP-DASH V2 Webpage is made by Vuejs. Files for Weboage are in vue-frontend folder of repository.
