### ISSUE TITLE
[BUG] not refreshing on dynamic change in number of cards/charts

### ISSUE THREAD

**Issue by petersoltys** [ayushsharma82/ESP-DASH#150]
after short investigation I have find out that command generated in arduino is not the same as in javascript
here is patch

```
diff --git a/src/ESPDash.cpp b/src/ESPDash.cpp
index 9d7faed..0e2ea93 100644
--- a/src/ESPDash.cpp
+++ b/src/ESPDash.cpp
@@ -437,7 +437,7 @@ void ESPDash::sendUpdates(bool force) {
 }
 
 void ESPDash::refreshLayout() {
-  _ws->textAll("{\"command\":\"refreshLayout\"}");
+  _ws->textAll("{\"command\":\"refresh:layout\"}");
 }
 
 void ESPDash::refreshStatistics() {
```

**Comment by petersoltys** [comment]
Hi Zen,
sure no problem.
there is simply difference in tag inside source code of browser JS and arduino C++ code.
as visible in patch simply replace line

`_ws->textAll("{\"command\":\"refreshLayout\"}");`

with updated tag name

`_ws->textAll("{\"command\":\"refresh:layout\"}");`

**Comment by Zen-Ong** [comment]
Thanks for the explanation, it works for me now.

**Comment by ayushsharma82** [comment]
Fixed with this commit: https://github.com/ayushsharma82/ESP-DASH/commit/21fe2f6ea816d2bd583dadb21db0f81d6b6654e2

Thanks for pointing out!
