### ISSUE TITLE
Crash when loading UI when sendUpdate is part of a task

### ISSUE THREAD

**Issue by skarfacegc** [ayushsharma82/ESP-DASH#151]
I have a task that handles gathering the data that I want to show on the dashboard.  Whenever I call sendUpdate I get a LoadProhibited error.  Any idea where I should be looking?

SDK 4.43
ESP32
using platformio with everything updated (not sure it's actually current versions of everything)

**Comment by skarfacegc** [comment]
moving sendUpdate out of my task and into the main loop seems to have worked, just needed to add a vTaskDelay to the main loop.  If I had passed dashboard into the task via params, would that have worked as well?

**Comment by skarfacegc** [comment]
So, there's definitely something going on here.  When I move send update into the task that is issuing the card.update I start to get crashes immediately after the dashboard loads.  Looks like it crashes on the first post load sendUpdate? 

https://github.com/skarfacegc/Probeinator/blob/b6d99cec3c06d846e662dd320c99dc3e1c1467a0/src/main.cpp#L189


This seems to be working fine when I put sendUpdate in the main loop.

**Comment by skarfacegc** [comment]
sorry.  I suck at github.

**Comment by skarfacegc** [comment]
Trying this again.

**Comment by ayushsharma82** [comment]
Hi @skarfacegc, 

Internally the `sendUpdate` function broadcasts data ( more than 10KB depending on how much cards you have on dashboard ) to all websocket clients. You may have low memory allocated for that particular task which causes the ESP to crash.

You can try increasing this value to something like `10240`:  https://github.com/skarfacegc/Probeinator/blob/b6d99cec3c06d846e662dd320c99dc3e1c1467a0/src/main.cpp#L225
