### ISSUE TITLE
Bug or restriction by design?

### ISSUE THREAD

**Issue by GitHubUserEH** [ayushsharma82/ESP-DASH#155]
I am not sure if this is a bug or if this is a limitation.

In a chart, a maximum of 62 values can be displayed vertically. If you want to display more elements, it works in the horizontal axe, but nothing is displayed vertically. On the contrary, the higher the number of elements, the less vertical bars are shown. See the attached PDF with the screenshoots. 

Code from the main loop to test:

void loop()
{
  int ArH[128];
  int ArV[128];

  for (int i = 0; i < 128; i++)
  {
    ArH[i] = i;
    ArV[i] = (int)random(1, 999);
  }

  Test_Chart.updateX(ArH, 62);   // <= 62 working   <= 128 working
  Test_Chart.updateY(ArV, 62);   // <= 62 working   >= 63 no vertikal bar is showing !

  dashboard.sendUpdates();

  delay(2000);
}

[ESP32Chart.pdf](https://github.com/ayushsharma82/ESP-DASH/files/11310321/ESP32Chart.pdf)

**Comment by ayushsharma82** [comment]
This should be fixed after recent performance improvements which are implemented in ESP-DASH. I'm marking this closed, but incase you are still facing the same problem - you can reopen the issue.
