### ISSUE TITLE
Custom Button Icons

### ISSUE THREAD

**Issue by adojang** [ayushsharma82/ESP-DASH#156]
Hi there! Just bought the pro version today after a few months of playing with ESP-DASH. Thank you for your wonderful contribution to the ESP32 codebase!

I wanted to ask if there might be a way to document how to add a custom icon to a generic card.
Ideally this would be similar to how a custom logo is added.

Additionally, if the icons are stored in the correct format, it might be possible for the user to also choose the color.

Something like this might be useful: https://remixicon.com/ where the user is able to choose a color and Icon.

The function call might look like:

Card card1(&dashboard, BUTTON_CUSTOM, rocket, f0bb40, "Custom Rocket Button",);

The card might look like this:

![image](https://user-images.githubusercontent.com/48274045/234694131-4e26ee9a-c0e0-49bd-b787-f8f49d5732b9.png)

In a separate file, icons.h, the user can translate icons from svg to the gzip/arduino/byte array format you're using with the tool you wrote.

I've got a few specific icons I'd love to see on the dashboard, but they don't exist yet:
- Door
- Lightbulb
- Speaker

**Comment by arzaman** [comment]
Hi @adojang 
did you find a solution to define custom icon / custom color ?

**Comment by mathieucarbou** [comment]
I would be interested in such feature too.

**Comment by adojang** [comment]
I ended starting to decompile the source code, but eventually decided to leave it. @ayushsharma82 , it seems this is a much requested feature :) Perhaps you could spend some time to make it available? The code or process to use a custom logo might be reused.
