### ISSUE TITLE
Is library working throw Ethernet

### ISSUE THREAD

**Issue by gorlanovmax** [ayushsharma82/ESP-DASH#159]
**Is your feature request related to a problem? Please describe.**
For my information, library ESPAsyncWebServer work via Wi-Fi.

In my controller, communication is carried out either via wi-fi or via etnernet
I used some another libraries.
It is all ok, when controller connected via Wi-Fi
But if controller connected via Ethernet, library is not working.

What is situation in this DASH Pro library?

**Comment by gorlanovmax** [comment]
And also interesting working via SIM800 module

**Comment by adojang** [comment]
Just from my own experience and struggling, the Ethernet interface might the the issue here. Perhaps writing some kind of wrapper that disguises the interface so it looks like the WiFi one might help?

**Comment by AZERTYUIO1234567890** [comment]
I have a problem here is the error message :
In file included from C:\Users\Downloads\esp32_oled_ac_v8.111\esp32_oled_ac_v8.111.ino:48:0:
C:\Users\Documents\Arduino\libraries\ESP-DASH\src/ESPDash.h:17:10: fatal error: functional: No such file or directory
 #include <functional>
          ^~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: exit status 1**

Can someone help me ?

**Comment by mathieucarbou** [comment]
> atal error: functional: No such file or directory

you need to specify how you build: IDE, board, versions of libraries, etc.

if you are on AVR, this is not supportd.

**Comment by juanmartin84** [comment]
Hello, are these new libraries compatible with ethernet.h lib?

(mathieucarbou) [AsyncTCP](https://github.com/mathieucarbou/AsyncTCP#v3.2.3) @ v3.2.3
(mathieucarbou) [ESPAsyncWebServer](https://github.com/mathieucarbou/ESPAsyncWebServer#v3.1.1) - v3.1.1

That would be great

**Comment by mathieucarbou** [comment]
> Hello, are these new libraries compatible with ethernet.h lib?
> 
> (mathieucarbou) [AsyncTCP](https://github.com/mathieucarbou/AsyncTCP#v3.2.3) @ v3.2.3 (mathieucarbou) [ESPAsyncWebServer](https://github.com/mathieucarbou/ESPAsyncWebServer#v3.1.1) - v3.1.1
> 
> That would be great

Yes I have 3 projects using them and supporting eth boards.

But make sure you use:

- mathieucarbou/ESPAsyncWebServer @ 3.3.14

and either:

- mathieucarbou/AsyncTCP @ 3.2.10
- https://github.com/mathieucarbou/AsyncTCPSock/archive/refs/tags/v1.0.3-dev.zip

See:

- https://github.com/mathieucarbou/ESPAsyncWebServer?tab=readme-ov-file#dependencies
- https://github.com/mathieucarbou/ESPAsyncWebServer?tab=readme-ov-file#performance

**Comment by juanmartin84** [comment]
Thanks Mahieu, I will try to implement it this week.
Best regards

**Comment by mathieucarbou** [comment]
https://github.com/mathieucarbou/MycilaESPConnect
