### ISSUE TITLE
Dark Mode - oss & pro

### ISSUE THREAD

**Issue by mathieucarbou** [ayushsharma82/ESP-DASH#167]
Dark Mode is there by default on ElegantOTA, it really miss in ESP-Dash ;-)
That's weird to switch from white to black.

I've tried settin `-webkit-filter: invert(90%);` on html tag, which is not bad but not ideal also.

**Comment by MaxMyzer** [comment]
Personally, I would style using the [CSS prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme), at least for the default. A UI toggle may be nice too, though.

**Comment by ayushsharma82** [comment]
Planned but not for v4 :), this will be in roadmap for v5.
