### ISSUE TITLE
Used examples

### ISSUE THREAD

**Issue by Onno-Dirkzwager** [ayushsharma82/ESP-DASH#17]
My compliments Ayush Sharma for this great library!

We think this library is worth recommending and added some of your examples to our library examples (slightly modified for working together with our library)

Of course we added links & credits to your account but we would like your feedback:
https://github.com/iotappstory/ESP-Library/blob/master/examples/Other%20Examples/ESP-DASH/ESP32_blink/ESP32_blink.ino

Let me know if you would like anything changed.

Regards
Onno Dirkzwager
IOTAppStory.com

**Comment by ayushsharma82** [comment]
Thanks and you can use the above examples with credits.
