### ISSUE TITLE
[BUG] dashboard.refreshStatistics(); also refresh all other components - not only stats (oss & pro)

### ISSUE THREAD

**Issue by mathieucarbou** [ayushsharma82/ESP-DASH#171]
`_dashboard.refreshStatistics();` should only refresh the statistic page

**Comment by ayushsharma82** [comment]
I know it's an lousy implementation but I don't want to rewrite the already complex generateComponentJSON function 😄

**Comment by mathieucarbou** [comment]
In that case I would suggest deprecating or completely remove the `dashboard.refreshStatistics()` function as it does not bring any value.

**Comment by ayushsharma82** [comment]
Yeah I'll mark it deprecated in future release.
