### ISSUE TITLE
Card.setEnable(true|false)

### ISSUE THREAD

**Issue by mathieucarbou** [ayushsharma82/ESP-DASH#179]
Hi,

I have a UI where some cards and actions have to be disabled or enabled. There is no such concept at the moment wher ewe could set such flag, and the card would be greyed-out, disabled from any update or user action.

So right now, I am handing that in the code by doing some conditional. The problem is that the callback expects the UI to be refreshed (which I do) but the refresh being empty, the wait icon that is waiting for  a refresh to be done is still there and never goes back.

`{"command":"update:components","tabs":[],"cards":[],"charts":[],"stats": []}`

![image](https://github.com/ayushsharma82/ESP-DASH/assets/61346/40ea6b05-9d6f-4feb-8c66-aee3bac34581)

Is there a way to implement that or have a working workaround, like updating only a specific component ?

**Comment by finchamp** [comment]
I agree, this would be useful and simple to implement. It appears to me that the documentation is also pretty scanty on using constructors/destructors on cards, as well. I've tried new/delete in my implementation on PlatformIO, and neither seem to have any effect on the dashboard, which is seriously disappointing. That would be an option, if it worked.

**Comment by mathieucarbou** [comment]
you need to use add and remove to change the layout.

**Comment by finchamp** [comment]
Is there any documentation on that? The only concrete info I could find uses the "delete" operator, and that is the dynamic example: https://github.com/ayushsharma82/ESP-DASH/blob/master/examples/Dynamic/Dynamic.ino

**Comment by mathieucarbou** [comment]
my documentation is the source code
![image](https://github.com/ayushsharma82/ESP-DASH/assets/61346/cac07ca4-0632-4e86-b1f5-debdde18e4cc)

**Comment by finchamp** [comment]
Hmm, I came across ~Card() in card.cpp, but hadn't dug deep enough yet to find that. Thanks. Still, it's a bummer that it's not reflected in the docs. Apologies for the semi-hijack.

**Comment by mathieucarbou** [comment]
Like most OSS project, the doc is often the code itself, especially for small projects. 

I am myself a big contributor of the open source community and write a lot of Arduino libraries, in my spare time, so I don't loose too much time on the doc. I am not paid for that. The value lies in solving the problem, and make this solution available to the community, not in documenting the problem. I also sometimes have comments like that in my projects, and my answer is that the beauty of oss projects is that everyone can contribute and send a PR 😉

(I am not the owner of this project but if you look at the contributions you will see that I contributed a lot to make it better)

**Comment by finchamp** [comment]
Indeed, I had noticed that, and appreciate your contributions. When I bought the pro license, I guess I just didn't expect to find very basic features missing from the docs. I'm not under the impression that we can make pull requests to the offsite documentation (https://docs.espdash.pro/), nor do I pretend to have an intimacy with Dash that would qualify me to do so, yet. If I am missing something, I welcome information to the contrary.

**Comment by mathieucarbou** [comment]
> Indeed, I had noticed that, and appreciate your contributions. When I bought the pro license, I guess I just didn't expect to find very basic features missing from the docs. I'm not under the impression that we can make pull requests to the offsite documentation (https://docs.espdash.pro/), nor do I pretend to have an intimacy with Dash that would qualify me to do so, yet. If I am missing something, I welcome information to the contrary.

Yes we can, a lot of GitHub projects are deploying their website through the GitHub repo directly. There are several mechanisms to do so, one of them being to put the website in a gh-pages brnach and ask GitHub to deploy from there.

You can review the doc and send PRs against this branch: https://github.com/ayushsharma82/ESP-DASH/tree/gh-pages

**Comment by ayushsharma82** [comment]
Just want to add here that docs website code is in ‘docs’ branch of this repo. People are open to contribute to it. Upon merger, the ‘gh-pages’ branch is automatically built & deployed by the bot.

**Comment by finchamp** [comment]
Having worked with this a little longer, it would be really helpful if the delivered user-side script flagged all tiles as disabled any time the sidebar status indicator changed to "Disconnected." For implementation as-requested by Mathieu, perhaps we could just copy and modify the setDisplay() method and related script?

**Comment by mathieucarbou** [comment]
I  am closing this feature request because I've implemented that in my fork (setDisplay) and @ayushsharma82 grabbed the changes for every pro users.

**Comment by finchamp** [comment]
Thank you very much for contributing that feature. I have already found it really useful.
