### ISSUE TITLE
Page not loading

### ISSUE THREAD

**Issue by frippan** [ayushsharma82/ESP-DASH#185]
When I try to load the page I only get the Logo on the top and Connected down in in corner. All the tabs are gone. Sometimes it could work but often no. Was thinking if that's a heap issue? 

The page I load is pretty big, can that be an issue? 

I have a bit over 100 cards on the page.

I'm using the latest pro version but had the same problem with the old 4.0.2 from september

I don't get any error in the console in chrome.

**Comment by mathieucarbou** [comment]
Hello,

You are running into the same issue as I did.

The library is using String, which, when reserving more space for copy, will invalidate themselves if the memory cannot be allocated, this an empty string gets sent to the websocket channel, which blanks the page (I might mistaken but that's what my analysis concluded while debugging).

You can add these lines in the code to debug and see your approximate payload size:

https://github.com/ayushsharma82/ESP-DASH/pull/182/files#diff-b22c24b3d761e54f8997b5313d563e3b2b58217a99f7e9e95beb68ad19ba6e13R331-R333

I suggest you set `DASH_LAYOUT_JSON_SIZE` to a multiple of 4k greater than this value.

If you look at all my Prs, I did 2 of them regarding memory footprint improvements: you can try merging in your fork, in order:

1. #183
2. #184


My PRs fixe a lot of issues (including the wrong refresh after uploading firmware, component ids, etc) and also add another flag regarding memory control: `DASH_PARTIAL_UPDATE_JSON_SIZE`.

The idea is to set `DASH_LAYOUT_JSON_SIZE ` to a value greater than the initial payload size when the layout refreshed entirely and then after set `DASH_PARTIAL_UPDATE_JSON_SIZE ` to a lower value matching (but greater than) the size of your partial updates.

It is better to also use `dahboard.update()` and not force a full refresh each time.

**Comment by frippan** [comment]
Thanks, I have been using it for a couple of days now and everything looks good.

**Comment by frippan** [comment]
Closed
