### ISSUE TITLE
esp-dash & esphome = synergy

### ISSUE THREAD

**Issue by rradar** [ayushsharma82/ESP-DASH#19]
It would be awesome if ESP-DASH could be tightly integrated with ESPHOME!

With esphome (esphome.io or github.com/esphome) it's awesomely easy to create nearly everything wit esp's and sensors. It comes already with a web server component (very simple) and it would be a dream to get ESP-DASH into the show! :star: :+1: :1st_place_medal: :grin:

**Comment by ayushsharma82** [comment]
Sure No Problem. Let me know if you need help. I am ready to integrate ESP-DASH in anything as long as credits are mentioned 😁

**Comment by rradar** [comment]
It will not get integrated direct in to esphome the author said because of very different architecture.

But it's always possible to do custom component for esphome like this one for example: https://github.com/rnauber/ESPHomeMatrixLED

Maybe you want to give it a try? :) And you should try esphome! Simply awesome!

**Comment by ayushsharma82** [comment]
I respect the decision of the author. I will try to port whenever i decide to use ESPHome 😊
