### ISSUE TITLE
Ability to hide Tabs & Cards in Pro version

### ISSUE THREAD

**Issue by dalise** [ayushsharma82/ESP-DASH#193]
It would be great to have the ability to hide both tabs and cards as required based on user requirements.
For instance I currently have two tabs based on the type of communication module fitted, Module A being an LTE Module and Module B being a Satellite Module. 
On startup if module A is detected, I would like the ability to hide Module B's tab as it has no relevance due to the system configuration.

**Comment by ayushsharma82** [comment]
Hi,

Please look into 'dynamic' card functionality which is available in both lite and pro versions. You can remove and add cards according to your functionality. 

Ref: https://github.com/ayushsharma82/ESP-DASH/blob/master/examples/Dynamic/Dynamic.ino
