### ISSUE TITLE
Password card

### ISSUE THREAD

**Issue by mathieucarbou** [ayushsharma82/ESP-DASH#199]
Like input ones, but with stars ;-)

_Note: this feature is implemented in my private fork fyi. The way I have implemented it, I only change the input type and leave card.data in the paceholder, to let the user choose what to display between nothing, a fixed number of stars, a random number of stars, or whatever he wants_

**Comment by ayushsharma82** [comment]
Released with v4.4.0 of [Pro](https://espdash.pro).
