### ISSUE TITLE
Expansion of cards

### ISSUE THREAD

**Issue by malbrook** [ayushsharma82/ESP-DASH#20]
Hi
I am very interested in using vue with the ESP32 as it looks like a better way of updating a web page instead of using AJAX. Do you have any plans to add other cards such as a form card to enter data and graphical instances such as a slider to change values or a progress bar.

best regards
Malcolm

**Comment by ayushsharma82** [comment]
Hi,
Yes, I am looking to expand ESP-DASH. The limitation is my free time. It would have been a lot better if users contribute in this library too.

There is a `progmem-dev` branch in development. I will be ditching SPIFFS for webpages and would store them in PROGMEM. It would be a lot better as users will now don't have to reupload spiffs on every new release of ESP-DASH. That branch also includes a new card - Gauges.

**Comment by malbrook** [comment]
Hi 
I am new to vue and in particular how to build the final app that includes all the files, but I would be happy to work on adding extra cards as I need them to convert an existing project for the EPS32 to an improved method for driving the web pages.

**Comment by ayushsharma82** [comment]
Great. Just checkout vue-ApexCharts. You will find some interesting stuff. and CSS framework is bulma.

**Comment by malbrook** [comment]
Hi
I have the vue apex charts demo working on my system and the examples work using npm, however when I try to use the source code for vue-frontend from the library to install into npm to run a server I get a blank screen on the browser once the server starts (npm run serve) and an error in devtools that there is a syntax error in app.js. Do you use npm to test the vue package?

**Comment by ayushsharma82** [comment]
I will check again. recently merged a pull request, which might be causing this..

**Comment by malbrook** [comment]
Hi I just tried using the distribution built by npm, by uploading it to my web server where it failed with the same error.
I then unzipped the app.js and copied the resultant file onto the server overwriting the previous zipped file and the system now works as I would expect it to. I get the navigation bar displayed, stats are disabled which is no surprise as this is a web server and not providing the details that an ESP server would and 'About' works fine.

**Comment by ayushsharma82** [comment]
Great. You are using progmem branch or master?

**Comment by malbrook** [comment]
Master branch with SPIFFS, I have an ESP32 up and running as well and just about to test the vue build on that to see how I get on, tomorrow I hope to start work on three extra cards, one as a circular barchart to use with OTA or other uploads, an area chart for some displays I require and a slider to allow control of a device by moving the slider up and down.

**Comment by ayushsharma82** [comment]
Great. Push updates to your fork. I will help accordingly. 👍

**Comment by ayushsharma82** [comment]
I got the error in vue serve. It was gzipping the app.js in development mode also. I have fixed it ( make sure to update your fork ). Now you can prototype on `npm run serve` :)

**Comment by malbrook** [comment]
Just to confirm I have now uploaded the apps.js that I built with npm from your code in the master distribution uploaded to the spiffs of an ESP32 running a one of your examples and it works but if I use the same app.js within npm (npm run serve) or on a standard web server it fails. Not a big deal as I can develop the vue files, include them into the source and generate an app that works with the esp32 to test them.

**Comment by ayushsharma82** [comment]
Try again. It will now work. Get the latest commit in master branch.

**Comment by ayushsharma82** [comment]
It's best to work on Vue development server. Just fill the card variables with dummy data in App.vue. It will show on Dashboard. 
You will get tired uploading back and forth between ESP and your PC.

**Comment by malbrook** [comment]
Hi
I will get the latest code to update my system and check it with npm.

**Comment by malbrook** [comment]
Working fine thanks for the assistance

**Comment by Swiftnesses** [comment]
Guys, +1 for more cards. It would be great to see some simple elements like checkboxes, dropdowns etc added! I spotted this, but have no idea how to integrate it...

https://semantic-ui-vue.github.io

**Comment by malbrook** [comment]
@Swiftnesses  I am working on a number of cards that I need for a project, the first is a simple slider (vertical or horizontal, to send values to ESP32. Others on my list are Progress Bar, Form Entry for configuration data,  an Alert Card to display messages, and a File Uploader.

**Comment by Swiftnesses** [comment]
@malbrook sounds good buddy, looking forward to seeing your results!

**Comment by ayushsharma82** [comment]
@Swiftnesses  @malbrook  We can make a switch to shards-vue (https://designrevision.com/docs/shards-vue/getting-started) incase we need some good components and slider controls. Please keep in mind to keep the size of whole webpage low.

**Comment by Swiftnesses** [comment]
@ayushsharma82 this looks perfect and would allow us to add dsome nicer looking components easily, as a pack! Now, how the heck do we do this :-D

**Comment by ayushsharma82** [comment]
For Arduino Code:
Include `add` and `update` functions. Create a json object, push to all websocket clients. 

Basic Json Template for a Card is: 
```
{ "id": "abcd", "name": "Card Name", "value": 40}

```
Add other variables according to Card's requirement.

For Vue:
Use the generate JSON template as a reference and sort it in a data variable in [App.vue](https://github.com/ayushsharma82/ESP-DASH/blob/master/vue-frontend/src/App.vue#L43) 

Now pass on that data variable as a prop to your card component in [Home.vue](https://github.com/ayushsharma82/ESP-DASH/blob/master/vue-frontend/src/views/Home.vue#L6)

I highly suggest everybody to read ESPDash.cpp and whole vuejs code to make a perfect sense. It's Hard, but atlast it will benefit everybody.

**Comment by Swiftnesses** [comment]
Seems a bit beyond my knowledge right now, sadly... Looking at all of the components offered via Shards, it would be excellent and offer many options for development. I'll need to wait for someone with more knowledge to offer an example or build a version with Shard included :(

**Comment by malbrook** [comment]
The [problem with shards is it needs bootstrap which is a large library, I have an existing application using bootstrap and ajax js to deliver web pages using AsyncWebServer which appears at first sight to work fine but after several months we have found repeated rebooting of the EPS32 and when a new Sony Smart phone was used the ESP32 crashes. It looks like the problem is related to large files and SPIFFS (look at the issues on AsyncWebServer, as we have tested ESP-DASH with the same phone and it displays happily hence my interest in this library. If we add in a bootstrap based vue I suspect the same problem will re-appear. There are plenty of vue libraries offering these components I have six myself but all of them generate much larger files than this system.
There is quite a bit of work needed to link the vue components into the ESP32 processor to extract data from the browser and send it the the ESP32 and to send data from the ESP32 to the vue components, each component needs some code to work even if you generate a vue app with all the items you need and jump past this library that lets you select what you want through the Arduino code.

**Comment by malbrook** [comment]
The slider that I am working on is based on vue-slider-component and provides vertical and horizontal slider working in either direction, screen shot below. The outer circle in lighter colour only appears when the inner circle is clicked to move the slider position.
![slider](https://user-images.githubusercontent.com/8124697/55883527-6640e480-5b9e-11e9-8991-76c68c6dffe6.jpg)

**Comment by ayushsharma82** [comment]
@malbrook  I have updated ESP-DASH today and have ditched SPIFFS. It now uses PROGMEM for serving webpage. There are some significant performance boost. There are some changes in Vuejs Code as well. Do check it out. You just need to copy "webpage.h" from dist folder to `src` of ESP-DASH folder after `npm run build`.

Regarding Bootstrap, First of all we will be using scss version of bootstrap with scss version of shards-ui.
Then later on we can select the specific components from the framework according to out need. ( Like i did with bulma in current release, i just chose the specific elements ).  Over that, We will be gzipping the whole webpage. I will try shards-vue over a different branch...

**Comment by ayushsharma82** [comment]
@malbrook  Please use this slider: https://wikiki.github.io/form/slider/

It will better fit bulma framework.

**Comment by malbrook** [comment]
OK I will see what needs to b changed, I should have the first version of the slider card working tomorrow, just sorting out the build to get th extra component into the distribution,  how does npm know it needs the extra component as it is currently building the original code even though I have made changes to the app.vue and home.vue to include the new component

**Comment by ayushsharma82** [comment]
@malbrook 

I didn't understood your question. You may share a screenshot of that problem.

**Comment by malbrook** [comment]
Hi
Sorted the problem I now have the new card in the packed application and can load it into the Arduino app, just need to test passing the value from the slider to the ESP32.

**Comment by malbrook** [comment]
@ayushsharma82
I had a look at the slider https://wikiki.github.io/form/slider/ but as far as I can see it has no event generator which we will need to transfer the slider position back to the Arduino. The one I am currently using does have an event and I can see the event appearing in the arduino when I move the slider from the sliderCard I am working on.
Can you confirm how many parameters can I send with EventBus.$emit() as I need both the id and the value in the event.

**Comment by malbrook** [comment]
Hi got it I needed to add the extra parameter into the new function EventBus.$on in App.vue that I had added for the slider.

**Comment by malbrook** [comment]
@ayushsharma82 
I have a working sliderCard based on the original for now which passes amessage via the web sockets connection in this format {"command":"sliderChanged","id":"slid1","value":"48"} and I have the additional code in the library to handle the message.
Two questions 
1/ how do you want the code passed over to you to integrate into  the library
2/ what package do you use to convert the code in the dash folder normally uploaded to spiffs into the progmem array for the new version of ESP-DASH

**Comment by ayushsharma82** [comment]
1. Create a Callback like Button Card
2. It will automatically convert to progmem data on npm run build. It's
finalize.js in vue-frontend.

**Comment by malbrook** [comment]
Hi
1/ Sorry I wasn't very clear I meant how do you want me to pass the completed code including arduino library changes to you, the current slider component is complete

**Comment by ayushsharma82** [comment]
Update your fork with changes, I will download it.

**Comment by ayushsharma82** [comment]
Did you debounce the slider? else it will flood websocket connection on ESP module.

**Comment by malbrook** [comment]
Yes slider comes with several events including 'change' which floods the websocket there is also 'drag-end' which I am using to initiate the update to the web socket.

**Comment by ayushsharma82** [comment]
Great. I also wanted to let you know that it's not necessary to use Vuejs components as a dependency. Vuejs has some vanilla events for html too. We just need CSS incase size of that component is large.

[Check this](https://codepen.io/Angelpsy/pen/mApRqJ/)

**Comment by malbrook** [comment]
Hi
Current size with this specific slider is 208KB but that includes some other items that will be used to generate some extra cards so increase with other cards I am working on should only be the vue code itself.
I have updated my branch which also includes the gauge you set up but I am still working with spiffs at the moment, will update to progmem version shortly.

There is one problem left to solve with the slider which you may already have looked at. Take the scenario where two different browsers are looking at the same page and one browser update the slider position, in that case the other browser should update to the new position, hence I am working on an update to the slider that should update both sliders to the same position and the other values linked to the slider.

**Comment by malbrook** [comment]
The demo program works for the gauge and the number but the second slider does not update for some reason.

**Comment by ayushsharma82** [comment]
@malbrook  Just saw your work! It's Amazing. I will check on that issue today

**Comment by ayushsharma82** [comment]
@malbrook  I have made some precise modifications to Slider Card:

1. I have reduced size of slider ( ESP-DASH is for mobile phones too. There considering the screen size, i have chosen a minimal size. )
2. Changed Color to a neutral blue which matches whole dashboard. 
3. I have added a spinner on top left of Card to indicate if value was successfully changed on ESP too.
4.  Disabled value changing on click. It will only work when we drag the slider.
5. Added Dynamic Sizing of Card and slider itself based on the type select by user.

Thanks a lot for your work brother! I will add the card and code which you made with relevant credits 😃  🎉  

Let me know if you wanna work on more cards for ESP-DASH.

**Comment by ayushsharma82** [comment]
![Slider](https://i.imgur.com/oEYCGmV.png)

**Comment by ayushsharma82** [comment]
@malbrook  @Swiftnesses  Slider Card is ready. Please test `slider-card` branch of this Repo and let me know if there is any problem. 

https://github.com/ayushsharma82/ESP-DASH/tree/slider-card

**Comment by malbrook** [comment]
@ayushsharma82 
I have updated all the files in my fork of ESP_DASH including an extra example using the slider to drive the gauge and a number card. Current fork does not yet use the progmem version.

**Comment by ayushsharma82** [comment]
@malbrook  You current SliderCard.vue changes prop directly. It's not preferred in Vuejs. Get the version which i modified: https://github.com/ayushsharma82/ESP-DASH/blob/slider-card/vue-frontend/src/components/SliderCard.vue

**Comment by ayushsharma82** [comment]
@malbrook  I think Slider Card is ready for a release. I will migrate your changes as well.
Are there any features left?

**Comment by malbrook** [comment]
Hi
Just been looking at your changes and running a test sketch based on one of the examples, see below, but I am not getting a value back from the slider and it is going back to zero. I removed the part of the code that sends a value into the slider in my latest version as this was causing the return to zero problem

`/*
* ESP-DASH V2
* Made by Ayush Sharma
* Github URL: https://github.com/ayushsharma82/ESP-DASH
* Support Me: https://www.patreon.com/asrocks5
*
* - Version Changelog - 
* V1.0.0 - 11 Nov. 2017 - Library was Born
* V1.0.1 - 13 Nov. 2017 - Fixed Empty SPIFFS Issue
* V1.0.2 - 13 Nov. 2017 - Improvements on SPIFFS Issue
* V1.0.3 - 24 Dec. 2017 - Pushing to Library Manager
*
* = Library Rewritten! =
* V2.0.0 - 25 Jan 2019 - Wohoo! A breakthrough in performance and capabilities!
*/

// This Example is a Demo of Realtime Capabilities of ESP-DASH with a Line Chart.
// Open Dashboard after Uploading and UI will auto update as the Chart Value Changes


#include <Arduino.h>
#include <WiFi.h>
#include <AsyncTCP.h>
#include <ESPAsyncWebServer.h>
#include <ESPDash.h>

AsyncWebServer server(80);

const char* ssid     = ""; // Your WiFi SSID
const char* password = ""; // Your WiFi Password

// Line Chart Data
int x_axis_size = 7;
String x_axis[7] = {"Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"}; 
int y_axis_size = 7;
int y_axis[7] = {2, 5, 10, 12, 18, 8, 5};


int newValue;
void sldCallback(const char* id, int thevalue){
  newValue = thevalue;
  Serial.println("Slider changed on Dash, ID - " + String(id) + "-" + String(newValue));
  //update gauge from slider
  ESPDash.updateGaugeChart("gauge1", newValue);
}


void setup() {
    Serial.begin(115200);
    WiFi.mode(WIFI_STA);
    WiFi.begin(ssid, password);
    if (WiFi.waitForConnectResult() != WL_CONNECTED) {
        Serial.printf("WiFi Failed!\n");
        return;
    }
    Serial.print("IP Address: ");
    Serial.println(WiFi.localIP());
    
    ESPDash.init(server);   // Initiate ESPDash and attach your Async webserver instance
    
    // add event handlers
    ESPDash.attachSliderChanged(sldCallback);

    // Add Respective Cards
    ESPDash.addSliderCard("slid1", "Slider 1",2);
    ESPDash.addLineChart("chart1", "Example Line Chart", x_axis, x_axis_size, "Power KwH", y_axis, y_axis_size);
    ESPDash.addGaugeChart("chart2", "Gauge 1", 30);
    server.begin();
}

void loop() {
    // Fill Data with random Values
    for(int i=0; i < 7; i++){
        y_axis[i] = random(2, 20);
    }

    ESPDash.updateLineChart("chart1", x_axis, x_axis_size, y_axis, y_axis_size);

    delay(3000);
}`

**Comment by ayushsharma82** [comment]
I did that change a hour ago. It will stay at last updated value. Check
again.

**Comment by malbrook** [comment]
mea culpa
I was using the previous version, all working fine

**Comment by malbrook** [comment]
@ayushsharma82 I have some other cards in mind let me know if any of these are already in development
1/ AlertCard to display text messages to user
2/ UploaderCard to handle file uploading
3/ OTAcard to control OTA from a server
4/ FormCard to allow changes to values stored in eprom or preferences. 
I also added an example to my fork for the slider card called ESP-view.

Now I have the first one completed I think I have a much better appreciation of how the system works so should be quicker in future

**Comment by ayushsharma82** [comment]
@malbrook  Nope, nothing in development right now....
We can work in conjunction to accomplish the above tasks.

How will you do OTAcard with AsyncWebServer?

**Comment by ayushsharma82** [comment]
@malbrook  For the UploaderCard, Just pass on the `File` buffer to user via function. As of V2 of ESP-DASH, the focus of library was changed from a "Full Framework" to just a "UI Library". User controls the cards and he only chooses on what to do with the input received from webpage..

Please take this view for future reference to more cards :)

**Comment by dezmob** [comment]
this project is amazing!
I wonder if some cards can be easily added like Boutton with status, and some Media Controls cards

![Artboard 2](https://user-images.githubusercontent.com/52044363/59924589-5a8f5b00-9436-11e9-900e-230d49e32972.png)

**Comment by kkaleta** [comment]
Can you please extend `ESPDash.updateStatusCard();` for a third parameter <_name>?

**Comment by manbade** [comment]
Hi, this code is superb!!!!
I´m using this for a weather display and works fine but I need a card with an icon like the StatusCard.vue but with all the icons about weather, sun, clouds.....
Now create several icon than looks like the 4 icons active, warning, danger.... but I think is better pass the name of the icon when create or update the cards.
Could you put some example about this? maybe its easy for you but really hard for me.
Thanks
Fernando

**Comment by manbade** [comment]
I´m thinking in other good improve, easy in my opinion, for sending the color code of the card background controlled from the sketch as a parameter. 
It´s is very useful when a card value exceed or reduce the value from defined triggers. Changing color  when temperature is high (red) or low (blue), for example.
The color can be by name (dodgerblue) or coded #FAFAFA #3273DC rgba(232,232,232, 0.8) ........

**Comment by polaco1782** [comment]
We are currently working on dash-next branch, its open to anyone who would like to collaborate with the project. If you have the skills, you can work on it and create a PR.

**Comment by dbartelmus** [comment]
With simplicity and used tool in this project you got me for sure.
I was trying to recreate your "dash-next" branch but it doesn't work as on screen attached in readme.

Are your changes already commited?
