### ISSUE TITLE
Time Sync card

### ISSUE THREAD

**Issue by mathieucarbou** [ayushsharma82/ESP-DASH#201]
Add a button allowing to send the browser time (`new Date().getTime()`) to a callback, which can look like this:= in client code:

```c++
  _ntpSync.attachCallback([](const char* value) {
    const String str = String(value);
    const size_t len = str.length();
    const timeval tv = {str.substring(0, len - 3).toInt(), str.substring(len - 3).toInt()};
    settimeofday(&tv, nullptr);
  });
```

Note: timezone could be set elsewhere in the example above.

![image](https://github.com/ayushsharma82/ESP-DASH/assets/61346/71649191-a91b-4353-85b2-3fa76bdbade4)

This is super helpful for time-sensittive apps relying on hours, when they work in AP mode or do not have internet access for NTP sync.

_Note: this feature is implemented in my private fork fyi_

**Comment by ayushsharma82** [comment]
Released with v4.4.0 of [Pro](https://espdash.pro).
