### ISSUE TITLE
Soft-AP example doesn't show cards

### ISSUE THREAD

**Issue by shanemmattner** [ayushsharma82/ESP-DASH#202]
I'm trying to run example code with the soft-ap and the cards don't appear to be loading.  See screenshot below but note I was connected to the ESP32 dash server, but to send the picture I disconnected from ESP32 ap and connected to regular wifi.

**To Reproduce**
- Use [this soft-AP example](https://github.com/ayushsharma82/ESP-DASH/blob/master/examples/AccessPoint/AccessPoint.ino)
- Try to access dash app from iphone 14 pro.  I tried chrome and firefox

**Expected behavior**
I expected to see cards with changing numbers

**Screenshots**
![esp-dash](https://github.com/ayushsharma82/ESP-DASH/assets/22162612/470e74aa-539b-4158-b0c8-15c5f9c9bba8)

**Additional context**

**Comment by Grochocinski** [comment]
I was running into the same issue but I discovered it was due to running an unsupported version of the ArudinoJson library (7.0.2). Once I rolled back the ArduinoJson library to 6.17.0, all my cards were displayed.
