### ISSUE TITLE
Status card stays in status "idle" (grey)

### ISSUE THREAD

**Issue by dash-user** [ayushsharma82/ESP-DASH#206]
Went from v.4.03 to 4.04 and now the status card color does not change anymore. Stays grey, no matter what status it is set to.

**Comment by ayushsharma82** [comment]
@mathieucarbou  Can you check? We need to check the `symbol` parameter alone for updates too. It is possible that value remains same but the symbol got changed.

**Comment by ayushsharma82** [comment]
I did fix it recently, maybe it got reverted in latest PR.

**Comment by ayushsharma82** [comment]
@dash-user I noticed what's the problem. We recently changed the status card values to:

1. `s` for success
2. `w` for warning
3. `d` for danger
4. `i` for idle

Please update your code accordingly. I'll update the docs.

**Comment by dash-user** [comment]
Works like a charm again. Thanks


Regards. 

Jo Engelke

Am Kuhkamp 11
D-31848 Bad Münder
Fon: +49 172 164 3277
***@***.***

PPlease consider the environment before printing this email

**Comment by ayushsharma82** [comment]
Great 👍

**Comment by mathieucarbou** [comment]
@ayushsharma82 @dash-user : the values transiting through websocket have been changed for memory / speed efficiency.

In your app, you must not use these values directly but the constant instead:

```
#define DASH_STATUS_IDLE "i"
#define DASH_STATUS_SUCCESS "s"
#define DASH_STATUS_WARNING "w"
#define DASH_STATUS_DANGER "d"
```

Constants didn't change, only the associated values has changed.

I am using both Pro and OSS version and symbol update works fine.

**Comment by dash-user** [comment]
Did that now. Thanks for the info. I used the char arrays because neither in the docs nor in the examples I could find any indication that there already were compiler directives defined for the statuses.
