### ISSUE TITLE
ESPhome custom component

### ISSUE THREAD

**Issue by arzaman** [ayushsharma82/ESP-DASH#207]
Hi,
 I came across this cool framework while searching for a dashboard solution for my ESPhome project (sensors, actuators, etc.). Currently, I'm using the standard web component to visualize the data in a simple tabular format. 

https://esphome.io/components/web_server.html

I'm not sure how much effort it would take, but it would be awesome if you could consider building a custom component for ESPhome. 

Thanks for your consideration. 
Regards, 
Davide

**Comment by finchamp** [comment]
Do you mean a card that would accept custom HTML/CSS?

**Comment by arzaman** [comment]
> Do you mean a card that would accept custom HTML/CSS?

Not exactly, the idea and request is to make your cool dashboard fully compatible with ESPHome Framework
https://esphome.io/index.html
so to leave the possibility to the ESPhome user to define their own web interface using ESP-DASH
