### ISSUE TITLE
Add button for remote update?

### ISSUE THREAD

**Issue by Swiftnesses** [ayushsharma82/ESP-DASH#21]
Hi,

I'm about to commence a new project whereby I'd the ESP to check a remote server for firmware updates, if there's one, display a button to commence the update (download and flash)....

Ideally I'd like to use your superb dashboard to do this, as I'm new to code, would this be possible?

**Comment by ayushsharma82** [comment]
ESP-DASH doesn't have a delete functionality yet. so you will have to use 1 status card and 1 button.
Use the status card to show the status of OTA and use a dedicated button on interface to update when whenever OTA is there.

**Comment by Swiftnesses** [comment]
Hi @ayushsharma82,

Appreciate the reply. Could I just show the button when an update is available, to stop the user clicking it when one isn't? With your knowledge of the ESP and Dash, how would you go about implementing this - I plan to have a first run at it tomorrow (hopefully I can find some nice code covering the OTA update mechanism!).

**Comment by ayushsharma82** [comment]
Yeah you can do that. just execute this `ESPDash.addButtonCard("ota", "OTA");` function when ever your code gets to know that OTA is available. Just don't execute it more than once or you will fill up the dashboard with buttons.

**Comment by Swiftnesses** [comment]
Excellent, and can I disable the button once clicked, or until the update fails, for example? I could try and block future presses via code, just wondering the best way to avoid them spamming the button :)

**Comment by ayushsharma82** [comment]
Nope that's why i told you it doesn't has a delete functionality. Once the component is added, It's added permanently.
A work around can be to reboot the Microcontroller and don't add the component again.  :P
Till then you will have to block via code.

I will definitely add a delete function in future.

**Comment by Swiftnesses** [comment]
Hey @ayushsharma82 did you manage to add that delete function?

**Comment by ayushsharma82** [comment]
Better to ask @polaco1782, He's working on V3 of ESP-DASH. Hopefully, he has added the delete functionality. You can checkout `dash-next` branch for more updates.

**Comment by Swiftnesses** [comment]
Hi @polaco1782, do you know if this can be added?
