### ISSUE TITLE
ESP-DASH size optimisation

### ISSUE THREAD

**Issue by mathieucarbou** [ayushsharma82/ESP-DASH#217]
ESP-DASH (and especially Pro) becomes more and more heavy. 
So heavy that even when optimising the partition, I do not have nay space left.
Here is a sample of a project analysis compiled with Arduino 3 and ESP-DAH + ElegantOTA, both OSS.

I am reaching the partition limit.

```
Error: The program size (2046177 bytes) is greater than maximum allowed (2031616 bytes)
RAM:   [==        ]  19.5% (used 63996 bytes from 327680 bytes)
Flash: [====*** [checkprogsize] Explicit exit, status 1
======]  100.7% (used 2046177 bytes from 2031616 bytes)
```

![image](https://github.com/ayushsharma82/ESP-DASH/assets/61346/6e8f4e20-ffd1-4da8-aa46-b66b9bb04562)

```
# Name,   Type, SubType, Offset,   Size,    Flags
nvs,      data, nvs,     0x9000,   0x5000,
otadata,  data, ota,     0xe000,   0x2000,
app0,     app,  ota_0,   0x10000,  0x1F0000,
app1,     app,  ota_1,   0x200000, 0x1F0000,
spiffs,   data, spiffs,  0x3F0000, 0x10000,
```

**Comment by mathieucarbou** [comment]
in another note, if you look, mdns takes quite  big place! So I will make it optional in MycilaESPConnect

**Comment by ayushsharma82** [comment]
Quick and simple fix: get an ESP32 with 16MB Flash 😂

**Comment by mathieucarbou** [comment]
> Quick and simple fix: get an ESP32 with 16MB Flash 😂

I'm caught! It's like me saying why the hell are you still using esp8266 boards lol!

But in the case of this specific project, I am limited with board choices because the same firmware is deployed on Lilygo boards with M2M capabilities and some are based on esp32 (4MB flash) and some on S3 (16MB flash) so the partition table is constraint to the lower size sadly.

**Comment by ayushsharma82** [comment]
That's dead end. As far as I know, are no 'common' scripts across all UIs ( ESP-DASH, ElegantOTA and WebSerial ). Every one of them are uniquely bundled to serve their purpose. Not to ignore the fact that framework versions can also change in between UIs.

At this point, upgrading the hardware somehow will be more of a wise approach than spending a lot of time on a niche issue.

**Comment by mathieucarbou** [comment]
I did a test right now... Just disabling pie charts and removing the `d3-scale-chromatic"` dependency **which is only used for pi charts**, accounts for a decrease of 11749 bytes! That's not negligible! That's 11k, only to draw pie charts...

This library alone could be extracted and be moved to a specific handler which is called only when pie charts are used (and deactivated through macros)

**Comment by ayushsharma82** [comment]
I think that library is just used for generating random colors. If you can
find a better logic, happy to replace it. It was put in ESP-DASH keeping in
mind that there will be more charts in future.

But library extraction and having multiple assets for ESP32 to serve is out
of the question. The reason why we compile everything into a single
index.html is because I have tested that ESPs in general can't serve more
than 2 huge concurrent HTTP requests. It's better to have more size than
just webpage not loading all together.

**Comment by mathieucarbou** [comment]
And a color gradient lib was not giving the wanting results ?
Something similar to this one:
https://codesandbox.io/p/sandbox/javascript-color-gradient-csgfd
That allows to select a number of colors, and a number of midpoints, which
is typically used for graphs.
Mathieu.

**Comment by ayushsharma82** [comment]
Didn’t give much thought into it at an earlier stage because I just wanted things to work. I do think we can replace it with a much simpler approach.

**Comment by mathieucarbou** [comment]
> Didn’t give much thought into it at an earlier stage because I just wanted things to work. I do think we can replace it with a much simpler approach.

OK.

I'm sorry to be so pushy on this one. The driver factor is that libraries all tend to get bigger and bigger, Arduino core itself also. I've talked recently about that with Jason (Tasmota) and Hristo (me-no-dev ) from Espressif and now, with new Wifi6, new WiFi encryptions and new features, stuff like mbedtls (ssl and encryption) cannot be removed anymore and comes by default. In fact, tested with a simple project Arduino 3 adds more than 170k. They also told me that 8MB flash is now becoming more and more required / a default for bigger apps. 

I am saying that because at one point, considering the wide majority of 4MB flash out there, people will stat looking at stripping down the firmware and this will start with the biggest dependencies, ESP-DAHS being one of them.

So I'm just raising a flag about what could come next.

I am myself currently impacted by that, found some ways, but with only 5.5% of free space left for flash (with a custom partition of 2MB) I am starting removing features. I.e. recently I had to remove support for mDNS to reduce firmware size, ESP-DASH is also one of them.

**Comment by ayushsharma82** [comment]
I get it. We can try to optimize the library till a certain point but as history has told us, the only way forward is by upgrading hardware to support latest features. Metaphorically speaking, we can’t keep a Pentium PC and expect it to run LLM right? 😂 

You need to start planning to decommission the current hardware and freeze current firmware in a branch. Once that is done, create a new major version for latest hardware.

I can tell you just by looking at it, there’s actually very little room for optimization here - 20-30KB at most. It’s only going to grow once more widgets are added.

**Comment by mathieucarbou** [comment]
Yes I agree.

One thing also that I was tinkering is the ability to propose the ambeded html file as a .gz file (to be put inside a LittleFS partition) instead of embedded in a header.

The reason is that we have to account for the fact that most apps are using an OTA partition, so a library additions means it will used twice its space in flash.

Moving in a FS partition would allow user to only flash FS updates through ElegantOTA and this space will be free for OTA partitions.

**Comment by mathieucarbou** [comment]
FYI, in relation to the 2 last comments here: https://github.com/platformio/platformio-registry/issues/105#issuecomment-2291004264

Providing the gzip file as an artefact in the release page would close this issue plus the fuzzy / grey area around GPL discussion.

 It would require a more complex effort from users and more doc, but still doable, and would close the door to any request for source code since the generated output is from a commercial project, and up to the users to download it or not.
 
 On my side, I must say that I am more interested in this solution for the firmware size benefit lol ;-)
