### ISSUE TITLE
Chart animation is on by default and makes using graph useless for real-time updates

### ISSUE THREAD

**Issue by mathieucarbou** [ayushsharma82/ESP-DASH#222]
ESP-DASH is a dashboard based on websocket, so many usages of graph will include streaming real-time data.

Here, I have an app with a JSY sensor which is refreshed each second to see the power.

But the graph is useless because the refresh rate is too fast for the animation.

https://github.com/ayushsharma82/ESP-DASH/assets/61346/c5049c45-afdc-4a15-b545-5eaec5a6cdea

I think this animations should be disabled by default in both OSS and Pro to account for a common usage. 

The only use cases I see for animations are for graph not refreshed often, like energy evolution over minutes or hours.

And this could be manually activated if wanted...

**Comment by ayushsharma82** [comment]
It’s a Pro only feature. Ref: https://docs.espdash.pro/features/chartanimations/

**Comment by mathieucarbou** [comment]
> It’s a Pro only feature. Ref: https://docs.espdash.pro/features/chartanimations/

I know that. I am not asking about having control over the animation. I am asking to disable it by default on OSS.

The fact is that Dash charts are completely useless in OSS for real-time data streaming.

**Comment by ayushsharma82** [comment]
I know but it is not about controlling animations. This toggle was added on request by Pro users to 'disable' animations. Unfortunately, I can't offer that in lite version by default due to my commitment.

Best way to mitigate the issue is to lower the refresh rate particularly for charts in your OSS offering.

**Comment by mathieucarbou** [comment]
> Unfortunately, I can't offer that in lite version by default due to my commitment.

Ok, I understand :-(


> Best way to mitigate the issue is to lower the refresh rate

FYI, In this case, lowering the refresh rate is not an option. The second granularity is important for such use case (power measurement). Power and energy are different measurements. What you are asking is to change the data form displaying power (which is an instantaneous measurement at a second granularity) into energy (which is the integration of power over time). That's something else entirely and not what this device is used for.

> particularly for charts in your OSS offering.

In this case, this was a standalone .ino file demoing how to resend the JSY power meter data remotely with a nice ESP-DASH Dashboard to monitor the power measurement. There is no Pro version, the code is simply a an .ino file, completely OSS. There is no binary firmware. Juste a .ino file.



I didn't know that DASH OSS limitations for charts made it unsuitable to display real-time streamed data like power measurements. I find it sad because there's a lot of use cases for that, and DASH-PRO sadly cannot be used in OSS .ino files because there is no pre-compiled firmware for them. Pro is only suitable when we provide the firmware, not the code, which means we also have to impose a subset of boards., at the opposite of a .ino file or pio project where the user can select his board with the same code. 

I just wanted to highlight that in some cases, even having the pro version does not helps at all and canot be used.
