### ISSUE TITLE
Spurious application reloads because of a timing issues between connection check interval and ping timeout

### ISSUE THREAD

**Issue by mathieucarbou** [ayushsharma82/ESP-DASH#227]
I found a timing issue in both ESP-DASH pro and oss regarding the ping/pong logic and the connection check interval.

On a bad timing moment and if the ESP is a little slow to answer for some reason, the ping will timeout, close the websocket connection and cause a full reload of the layout after re-opening it.

And when it happens, things can keep synchronised and the app would reload (in my case) about each 30 second.

I've send PRs in OSS portal and updated my pro branch to fix that and decrease the offline detection time also. Works fine so far.

**Comment by elfalto** [comment]
I am also experiencing this issue but only in softAP mode. Probably due to the increased Wifi load in comparison to joining a wifi hosted elsewhere. would appreciate specific tips on how to fix this on non-pro version.

**Comment by mathieucarbou** [comment]
> I am also experiencing this issue but only in softAP mode. Probably due to the increased Wifi load in comparison to joining a wifi hosted elsewhere. would appreciate specific tips on how to fix this on non-pro version.

You need to ping @ayushsharma82 because only him can update the UI for the OSS version, based on the equivalent fix I did for the pro version.
