### ISSUE TITLE
Staus Card - no icon or colour change for success, warning, danger or idle

### ISSUE THREAD

**Issue by deepwater-code** [ayushsharma82/ESP-DASH#236]
I am currently using the Dash Pro version and have noticed that the status card is not working as expected. 
The text is displayed, but the icon and colour changes do not update for success, warning, danger etc, it is grey with an "i"

**Comment by ayushsharma82** [comment]
@deepwater-code, Let me know what version of ESP-DASH Pro are you using?

**Comment by mathieucarbou** [comment]
@deepwater-code : are you using the macros ?

https://github.com/ayushsharma82/ESP-DASH/blob/master/src/ESPDash.h#L40

**Comment by deepwater-code** [comment]
I am currently using ESP-DASH-Pro-v4-6-0
I am not using macros.
I am just testing with the example benchmark.ino

I have checked this in both Firefox, Brave and Chrome and it behaves the same.

![icon image](https://github.com/user-attachments/assets/d3c52c9d-4ff1-4c77-9b03-9bb08008d24a)
