### ISSUE TITLE
Some suggestions about your code

### ISSUE THREAD

**Issue by Guillaume57** [ayushsharma82/ESP-DASH#24]
Hello, nice library :)

Here are some suggestions

- Don't duplicate the add* methods, simply put a default value in the prototype (for example ```void addNumberCard(const char* _id, const char* _name, int _value = 0 );``` )
- Use ```#if defined(DEBUG_MODE)``` instead of ```if(DEBUG_MODE)```
- Don't use Strings

**Comment by ayushsharma82** [comment]
@Guillaume57  Thanks for the suggestions 😃 👍  I will try to do those in free time. If you would like to help in improving the code, Please submit a pull request with changes.

**Comment by polaco1782** [comment]
#dash-next uses numeric IDs
