### ISSUE TITLE
Framework Suggestion

### ISSUE THREAD

**Issue by MichMich** [ayushsharma82/ESP-DASH#3]
First of all, I love this idea and your implementation.

As a webdeveloper (by day), I noticed you use jQuery. Although it's powerful, there are better alternatives around these days. I'd like to suggest looking into [Vue.js](https://vuejs.org), allowing you to make a lightweight reactive website. It would be even better if the communication with the ESP is done via web sockets to get realtime updates. 

Anyhow, keep up the great work!

**Comment by Pablo2048** [comment]
Its not jquery - its http://zeptojs.com/ vue.js is about 20kB/gzipped, zepto is ~9kB/gzipped...

**Comment by MichMich** [comment]
Ah, your right. The added benefit of Vue is that it's reactive. Making the development much easier and less error prone. Of course I can always make my own fork, it was nothing but a suggestion to the developer.

**Comment by Pablo2048** [comment]
Ok, i'm not an experienced html/javascript coder so i want to ask you - where you see advantage in making @ayushsharma82 work (which is very nice BTW) responsive? Can you please put some light into this for me?

**Comment by ayushsharma82** [comment]
@MichMich Yeah i see. I know Vue.js. the whole problem is to find a perfect mix between performance and quality of webpage presented. The Responsiveness is Received by the CSS Framework and there is nothing complex going on here to switch to Vue.js.  The Library is Limited to Creating those dynamic tabs only therefore zepto.js was a good choice. 

For Websockets Question:
You can see the my esp8266 forum post - http://www.esp8266.com/viewtopic.php?f=8&t=16396 , someone already tried websockets (I appreciate what everybody is doing with the library).You can see, it consumed 7% more heap. leaving less space for your own code in esp8266.

Still a Fork would be helpful for those who want to make Library operate on Vue.js and websockets! :)

**Comment by MichMich** [comment]
Hi @ayushsharma82 and @Pablo2048. Just to be clear: I wasn't really talking about responsive design. But about a reactive approach. This means, you as a developer don't need to worry about updating the interface whenever data is updated inside javascript. There simply is a model(data)-view(interface/html) binding. Whenever data is updated, the interface is automatically updated.

I understand the issue about the heap. That being said. Most projects won't use the biggest part of the heap. My guess is that your library will be mainly used for interfaces to toggle a GPIO or reading sensor data. In that case, the experience (performance) would be much better if sockets are used. Maybe there is a way to incorporate both solutions and let the user decide?

**Comment by ayushsharma82** [comment]
@MichMich Oh ok . Got your point, And that certainly is possible.
If we replace Zepto (9kb) with Vue.js (20kb). the Page loads 0.5 seconds late. 
and 
I like the idea on choosing to use websockets or not. It can definitely be added. Just need to see if users are ok with this approch...

**Comment by MichMich** [comment]
Don't worry to much about it. It was just a suggestion. If you like the approach. Feel free to implement it. But as it's currently is, it's already awesome! :)

**Comment by Pablo2048** [comment]
@MichMich thank you to clarify this. I don't have problem with xhr (but i like websockets more ;-) ).
@ayushsharma82 if you replace webserver from core with ESPAsyncWebServer then the response will be even faster - I'm serving 176kB and 22kB javascript files, 17kB CSS, some kind of media (small mp3 files) and graphics - 1st stage under 0.8 seconds and whole thing under 1.5 second (it's Blockly with two compilers, completly served from ESP SPIFFS).

**Comment by ayushsharma82** [comment]
@Pablo2048  Currently ESP-DASH loads in just 1 Second. All Files. You can try gzipping your project files. it greatly reduces the size.

**Comment by Pablo2048** [comment]
:-) unpacked Blockly is 794kB ...

**Comment by ayushsharma82** [comment]
Oh 👍  . Well Done

**Comment by ayushsharma82** [comment]
Thanks for everybody's Views on Websockket Implementation. Will Look forward to it in future. :)

**Comment by ayushsharma82** [comment]
@MichMich  Thanks for the suggestion! I have release ESP-DASH V2 with Vuejs Frontend and Websocket Communication 😊🎉

**Comment by MichMich** [comment]
Awesome! Nice work.
