### ISSUE TITLE
failed to load... content lenght mismatch

### ISSUE THREAD

**Issue by marcelrv** [ayushsharma82/ESP-DASH#30]
Hi
I updated to the latest version and have some frequent issues loading the page.
Note, sometimes it does seem to load (with a few refreshes).

![image](https://user-images.githubusercontent.com/5871213/57477172-6664fa80-7298-11e9-89cc-3787cda0165d.png)

I've re-produced it using the realtime esp8266 in the sample folder, with the only difference of adding 5 extra cards in the init.
```
   ESPDash.init(server);   // Initiate ESPDash and attach your Async webserver instance
    // Add Respective Cards
    ESPDash.addLineChart("chart1", "Example Line Chart", x_axis, x_axis_size, "Power KwH", y_axis, y_axis_size);
    ESPDash.addGaugeChart("chart2", "Gauge 1", 30);
       ESPDash.addNumberCard("PowerConsumption", "Power Consumption", 0);
    ESPDash.addNumberCard("PowerSolar", "Power Solar", 0);
      ESPDash.addNumberCard("PConsT", "Consumption Today", 0);
    ESPDash.addNumberCard("PSolT", "Solar Today", 0);
    ESPDash.addStatusCard("mqttStatus", "mqtt Status", 3);
    server.begin();
```
is 5  cards just too much for an ESP8266? or is something else wrong.

Note, it does seem like a lot of data is loaded (800+kb)., Does it make sense to load the vue files from a cdn instead of from the device?

**Comment by ayushsharma82** [comment]
Number of cards used in code doesn't affect the size of the webpage. It's a dynamc webpage, so it will send a request to load the card data once the webpage is fully loaded on your browser..

It loads Vuejs Webpage from device itself only.  

I will test this same config on my esp8266. Please share your esp8266 board details.

**Comment by ayushsharma82** [comment]
It actually sends 255kb of data only, which is in fact gzipped. So it becomes around 800kb+ data when unzipped by browsers.

Maybe be in future, we will add a functionality where; if the module detects an internet connection, it will switch to a CDN instead of serving locally.

**Comment by marcelrv** [comment]
I've tested this on 2 boards: nodeMCU (esp8266 12E) and a Wemos D1 mini.
Indeed the gzipped data is about 255K... that is the same I see when successful.

2nd thought...on the vue part: I  understand there are several versions (e.g. debug/minimized etc). Where the min version is about 55kb only.

**Comment by polaco1782** [comment]
![Screenshot at 2019-05-12 22-27-12](https://user-images.githubusercontent.com/685084/57590969-5bfb6880-7505-11e9-985b-b27f56b73386.png)
I've tested on mine and it works fine, that failure didnt  happened. I'll look on the webserver code, maybe there is a limit over 256k? see, mine transfers only 205k.

**Comment by ayushsharma82** [comment]
@marcelrv  Are you updating cards too frequently? That might be causing the AsyncWebServer to reset. ( As AsyncWebServer and AsyncWebsockets run off the same AsyncTCP Server )

**Comment by marcelrv** [comment]
Indeed, that may be the cause. I have a 'bug' in my code that actually updates the all of the cards twice. That means that 12 updates are done quickly after each other.

I'll see if I do less updates if that avoids the issue.
note: I'm using platformIO for development, I can't really imagine that that makes a difference... but just to let you know in case.....

**Comment by marcelrv** [comment]
I did some more testing, 
1) Seems the initial load (after reboot) is more often (mostly) successful  than using the refresh (from the browser)
2) If I do very frequent updates (e.g. in my testfile I updated 12x in each 2 sec) the page loading is less likely to be successful
Also it (significantly) increases the load time (now approx 30+ seconds for the page to load)


I've now updated my program to only do updates when data is actually changed, seems that indeed is more successful

**Comment by marcelrv** [comment]
note, in my program I also use the pubsub library (mqtt). I'll replace that with AsyncMqttClient as the first may do some blocking as well, which I can imagine interferes with AsyncWebServer and AsyncWebsockets run off the same AsyncTCP Server

**Comment by ayushsharma82** [comment]
Another thought:
Is there anything blocking in the code?
Some long running tasks might be causing the issue.

Please check and let me know. I will investigate further.

**Comment by ayushsharma82** [comment]
Yup. That can cause issues.

Let us know if it is resolved by switching to AyncMqttClient.

**Comment by ayushsharma82** [comment]
@marcelrv  Any update?

**Comment by ayushsharma82** [comment]
Closing due to no response.
