### ISSUE TITLE
can not add project description in about page

### ISSUE THREAD

**Issue by smartman2012** [ayushsharma82/ESP-DASH#31]
First of all thx for this great work, i want to add some description about my project before the lines of about DASH in about page (tab) but when i add lines and upload the code everything is the same and there is no extra description

**Comment by ayushsharma82** [comment]
To Modify Webpage:
- go to `vue-frontend` folder. 
- open `Command Line`

#### Install (First time only)
- In Command Line enter `npm install -S`

#### Build: 
- Once finished, You can modify the Vuejs Files
- Then run `npm run build`
- Copy the `webpage.h` from `dist` folder and paste it in `src` of library.
