### ISSUE TITLE
convert from Access point to local webserver on existing wifi network?

### ISSUE THREAD

**Issue by aspiringguru** [ayushsharma82/ESP-DASH#33]
Is it possible to enable this as a local webserver on an existing wifi network?

I just tried swapping 
WiFiServer server(80);
for 
AsyncWebServer server(80);

threw error message as below (not surprised). Much as I like the access point based design, I was hoping to use this dashboard on a node in my local wifi and port forward  access to the dashboard. Having to jump onto the new ssid for this access point is not my use case.

Great work otherwise.
=============================================================
Arduino: 1.8.9 (Windows Store 1.8.21.0) (Windows 10), Board: "FireBeetle-ESP32, 80MHz, 115200"

blah\ESPDashDemo1.ino: In function 'void setup()':

ESPDashDemo1:50:24: error: no matching function for call to 'ESPDashClass::init(WiFiServer&)'

     ESPDash.init(server);   // Initiate ESPDash and attach your Async webserver instance

                        ^

In file included from blah\ESPDashDemo1.ino:16:0:

blah\Arduino\libraries\ESP-DASH-master\src/ESPDash.h:84:14: note: candidate: void ESPDashClass::init(AsyncWebServer&)

         void init(AsyncWebServer& server);

              ^

blah\Arduino\libraries\ESP-DASH-master\src/ESPDash.h:84:14: note:   no known conversion for argument 1 from 'WiFiServer' to 'AsyncWebServer&'

Multiple libraries were found for "WiFi.h"
 Used: blah\ArduinoData\packages\esp32\hardware\esp32\1.0.2\libraries\WiFi
blah\ArduinoLLC.ArduinoIDE_1.8.21.0_x86__mdqgnx93n4wtt\libraries\WiFi
exit status 1
no matching function for call to 'ESPDashClass::init(WiFiServer&)'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by ayushsharma82** [comment]
You cannot swap AsyncWebServer with the default webserver for ESP-DASH.

You can try porting your code to use AsyncWebServer, it's much faster and reliable.

**Comment by malbrook** [comment]
AsyncWebServer works with both AccessPoint and Station settings, when set for both the AsyncWebServer serves the pages to both the AccessPoint IP and the Station IP on the local  network. AsyncWebServer does need a different setup to standard web server as all calls are Asynchronous so you need to set up the pages via server.on calls, the examples in the AsyncWebServer library make the use clear.
