### ISSUE TITLE
options to modify charts

### ISSUE THREAD

**Issue by aspiringguru** [ayushsharma82/ESP-DASH#34]
I'm wondering how to customise the charts, add new chart types etc. at moment I want to add vertical scale to the addLineChart, but need to understand how the files interact and build process.

It looks like it should be possible to add newChartComponent.vue  to ESP-DASH-master\vue-frontend\src\components\ with a corresponding new line in \src\ESPDash.h

and possibly configure options within LineChart.vue to add legends, scales, y-axis labels etc.

Am I on the right track here? A few notes on how to add more chart types and configurations would be awesome. 

in main.js > import import VueApexCharts
range of chart types available
https://apexcharts.com/vue-chart-demos/line-charts/data-labels/

in ESP-DASH-master\src\ESPDash.h method for addLineChart
void addLineChart(const char* _id, const char* _name, int _x_axis_value[], int _x_axis_size, const char* _y_axis_name, int _y_axis_value[], int _y_axis_size);

component 
ESP-DASH-master\vue-frontend\src\components\LineChart.vue 

ESP-DASH-master\vue-frontend\README.md describes the build process(?)

**Comment by ayushsharma82** [comment]
Hi @aspiringguru,

Thanks for showing an interest in contributing to this library.

- You can copy or edit this Vuejs File for every new Chart : [This](https://github.com/ayushsharma82/ESP-DASH/blob/master/vue-frontend/src/components/LineChart.vue)

- Edit the `chartOptions` json data in that new file to modify chart according to your liking. Ref: [This](https://github.com/ayushsharma82/ESP-DASH/blob/master/vue-frontend/src/components/LineChart.vue#L42) 

- All available Chart options can be found [Here](https://apexcharts.com/docs/options/)

**Comment by ayushsharma82** [comment]
To build the webpage: 
- Go to `vue-dashboard` directory
- Run `npm run build`
- Copy `webpage_zopli.h` to `src` of library folder where ESPDash.h can be found.
- Rename `webpage_zopli.h` to `webpage.h`

Done.

**Comment by ayushsharma82** [comment]
To show Y Axis:
Paste the below code under [this line #66](https://github.com/ayushsharma82/ESP-DASH/blob/master/vue-frontend/src/components/LineChart.vue#L66):

```
yaxis: [
    {
      show: true,
      axisTicks: {
        show: true
      }
   }
],
```
