### ISSUE TITLE
page loading

### ISSUE THREAD

**Issue by willknob** [ayushsharma82/ESP-DASH#39]
hi. my page doesn't load when i try to access the ip .

Help me please.

tks

**Comment by ayushsharma82** [comment]
Please provide a bit more information.
1. Which ESP are you using? ESP32 or ESP8266
2. In Which mode are you trying to access your ESP?  Access Point / Station Mode

**Comment by willknob** [comment]
I'm using ESP8266 and already tried to use all the examples of the library.
I got the ESP's IP address from Station Mode

**Comment by willknob** [comment]
Hi, any help? Tks

**Comment by ayushsharma82** [comment]
I couldn't find any possible cause yet. We will update this issue when the cause of this problem is found...

**Comment by willknob** [comment]
I got this message on serial monitor using de blink example for ESP8266:

IP Address: 192.168.0.9
 [DASH] Found an empty slot in Button Cards. Inserted New Card at Index [0].

**Comment by Xsenonn** [comment]
Hi, I'm having the same problem, unable to reach page, monitor explorer shows the same message as above and I keep getting timeout. Has anyone found solution maybe?

**Comment by ayushsharma82** [comment]
This probably happens when you are trying to access webpage from different Access Point. Your browser and ESP Microcontroller should be connected to the same network.

Let me know if problem persists.
