### ISSUE TITLE
[Request] Compress script for folder data

### ISSUE THREAD

**Issue by Rotzbua** [ayushsharma82/ESP-DASH#4]
| Topic | request
| ----- | ----
| Version | v1.0.2  

Hi,
thanks for your library.
The folder data/dash/ contains raw source files and a compressed .gz files. If I change the source files, there is no easy way to rebuild the complete folder. Can you publish the `.sh` script?
Best

**Comment by ayushsharma82** [comment]
Actually. You can Rebuild .gz Files with 7Zip Software.
There was no .sh script used. Just Edited the Pages and compressed them individually .

**Comment by ayushsharma82** [comment]
I will try to make a Script to Compress all Files in one go. Thank you for your Suggestion.
