### ISSUE TITLE
Features that I would like to add

### ISSUE THREAD

**Issue by hoonchiat** [ayushsharma82/ESP-DASH#43]
I love the easy and fast implementation of ESP-DASH and have been playing with it on a ESP-01., 2 area that I like to see expanded,

1. Ability to display a String/Text message, I notice that the data structure for the card is the value have to be an integer, would it be better to be a string as we could then format any value, including float value and string message to be display on a card?

2. Is it possible to dynamically add or delete a card within run-time?

If possible could you drop some comment if this would be a major overhaul effort to the existing code.

Just my 2 cents.

Thanks

**Comment by ayushsharma82** [comment]
1. Strings increase memory usage and ESP-DASH library is already pretty hefty. Heap usage will increase a lot if we use strings in every card. Over that it's best to make cards for a specific purpose only, so that it's standardized for future releases.

2.  Yes, dynamically adding and deleting card within run-time will be added in V3 of ESP-DASH (dash-next branch).  Currently in V2, we are focusing on adding more cards.

**Comment by hoonchiat** [comment]
Is it possible to create a card that display text?

**Comment by ayushsharma82** [comment]
No.. but I will add that on list too. You can expect it in couple of days, or incase you know vuejs, you can create the card yourself and create a pull request in this repo.

Any amount of work is well appreciated and will make development faster.

**Comment by hoonchiat** [comment]
Thanks, Looking forward to the new types of cards. Will try to pick up vuejs and play around with it.

**Comment by polaco1782** [comment]
I think I'll finish the v3 code this weekend, so we need some testing on it. If you could help us on testing.

**Comment by hoonchiat** [comment]
Yes, I am interested to test the new code.

**Comment by cityuur** [comment]
It would be great to have a card for user input or slider to change some value eg. int/float

**Comment by szetszho** [comment]
It would be vreat to have card for user input or slider to change int/float value

**Comment by kkaleta** [comment]
> It would be great to have cards for user input or slider to change int/float value

I agree. A text field (user input) is necessary.

**Comment by induchoy** [comment]
> I think I'll finish the v3 code this weekend, so we need some testing on it. If you could help us on testing.

dear thanks for this great library. we are waiting for V3 release. we are facing problem with float data  means we are not able to show float data on dashboard. please help me with float data if possible it would be very appreciated.

**Comment by ayushsharma82** [comment]
@hoonchiat  @szetszho  Your requested functionality has been added in V3. 🎉 ( #92 )
