### ISSUE TITLE
Adding new cards

### ISSUE THREAD

**Issue by RobertSmart** [ayushsharma82/ESP-DASH#47]
Hi,

I want to help add a few new cards. I'm very familar with Vue, so no problems there. 

What are the build steps from cloning the project please?

Thanks,

**Comment by ayushsharma82** [comment]
I'm currently re-working on the current dashboard for V3 release.  After the release of V3, we can discuss about creating new cards with that design language. 

For developing V2 Dashboard:
1. Go to `vue-frontend`directory
2. Run `npm install`
3. Run `npm run serve`

That's all. After that you can edit vue files and dashboard will automatically reload.

For compiling:
1. Run `npm run build`
2. Copy `webpage.h` from `dist` folder to `src` of repository.
