### ISSUE TITLE
Generalize the number card

### ISSUE THREAD

**Issue by mlesniew** [ayushsharma82/ESP-DASH#49]
Hi, 

l was wondering if it would be possible to add more card types similar to the temperature and humidity cards, e.g. a card for atmospheric pressure, voltage or power.  After checking the code I've come to the conclusion that all of them are basically the same, the only difference is the measuring unit. 

I think I would be able to modify the code of the number card so that it would be additionally configured with a unit (a string, like V or kW for example).  This way the number card could be used to display any kind of measurement.  Additionally, the existing temperature and humidity card types could be also built using the extended number card.  Of course, the functions related to the temperature and humidity cards should probably still stay in the class for backward compatibility, but their internal implementation could be simplified.  

What do you think about this approach? Would it be worth implementing?  If you think it's a good idea, I could try to do it and prepare a pull request.

**Comment by ayushsharma82** [comment]
@mlesniew  It will need some UI Adjustments too. I will suggest you add this type of feature in V3 `dash-next` branch of ESP-DASH.

I will modify the UI accordingly in `dash-next`. You can create a pull request for the server-side block of code.

We have shifted our focus to the new `dash-next` branch.

**Comment by ayushsharma82** [comment]
Added a `Generic` Card with V3 Release and now almost all cards support `symbol` attribute.
You can take a look at examples and upgrade your code.

Thanks for your input!
