### ISSUE TITLE
Clickable pads

### ISSUE THREAD

**Issue by radimsejk** [ayushsharma82/ESP-DASH#5]
Hi,

this library is awesome, but it would be great, if there would be chance to add some clickable panels or buttons which would initiate some actions. Some input panels would be great too.

Thank you for your work.

**Comment by ayushsharma82** [comment]
I will definitely look into developing some clickable pads. Thanks for the Suggestion

**Comment by ayushsharma82** [comment]
Added Clickable Buttons with ESP-DASH V2 Release! Thanks for the suggestions! 😊🎉
