### ISSUE TITLE
problem with some libraries?

### ISSUE THREAD

**Issue by halukmy** [ayushsharma82/ESP-DASH#51]
# include <Arduino.h>
# include <WiFi.h>
# include <PubSubClient.h>
# include <EEPROM.h>
# include <SPI.h>              // include libraries
# include <LoRa.h>
# include <xxtea-lib.h>
//#include <BH1750.h>
# include "Timer.h"
# include "esp_system.h"

# include <SparkFunTSL2561.h>
# include <Wire.h>

when i try with lora and wifi, got some problem, can you check?

**Comment by ayushsharma82** [comment]
Please provide a basic example `sketch`.

**Comment by halukmy** [comment]
/*
  LoRa Duplex communication

  Sends a message every half second, and polls continually
  for new incoming messages. Implements a one-byte addressing scheme,
  with 0xFF as the broadcast address.

  Uses readString() from Stream class to read payload. The Stream class'
  timeout may affect other functuons, like the radio's callback. For an

  created 28 April 2017
  by Tom Igoe
*/
#include <SPI.h>              // include libraries
#include <LoRa.h>

#include <Arduino.h>
#include <WiFi.h>
#include <AsyncTCP.h>
#include <ESPAsyncWebServer.h>
#include <ESPDash.h>

AsyncWebServer server(80);

const char* ssid = ""; // Your WiFi SSID
const char* password = ""; // Your WiFi Password

const int csPin = 7;          // LoRa radio chip select
const int resetPin = 6;       // LoRa radio reset
const int irqPin = 1;         // change for your board; must be a hardware interrupt pin

String outgoing;              // outgoing message

byte msgCount = 0;            // count of outgoing messages
byte localAddress = 0xBB;     // address of this device
byte destination = 0xFF;      // destination to send to
long lastSendTime = 0;        // last send time
int interval = 2000;          // interval between sends

void setup() {
  Serial.begin(9600);                   // initialize serial
  while (!Serial);

  Serial.println("LoRa Duplex");

  // override the default CS, reset, and IRQ pins (optional)
  LoRa.setPins(csPin, resetPin, irqPin);// set CS, reset, IRQ pin

  if (!LoRa.begin(915E6)) {             // initialize ratio at 915 MHz
    Serial.println("LoRa init failed. Check your connections.");
    while (true);                       // if failed, do nothing
  }

  Serial.println("LoRa init succeeded.");
 if (WiFi.waitForConnectResult() != WL_CONNECTED) {
        Serial.printf("WiFi Failed!\n");
        return;
    }
    Serial.print("IP Address: ");
    Serial.println(WiFi.localIP());
    
    ESPDash.init(server);   // Initiate ESPDash and attach your Async webserver instance
    // Add Respective Cards
    ESPDash.addNumberCard("num1", "Number Card", 264);
    ESPDash.addTemperatureCard("temp1", "Temperature Card", 0, 20);
    ESPDash.addHumidityCard("hum1", "Humidity Card", 98);
    
    server.begin();
}


void loop() {
  if (millis() - lastSendTime > interval) {
    String message = "HeLoRa World!";   // send a message
    sendMessage(message);
    Serial.println("Sending " + message);
    lastSendTime = millis();            // timestamp the message
    interval = random(2000) + 1000;    // 2-3 seconds
  }

  // parse for a packet, and call onReceive with the result:
  onReceive(LoRa.parsePacket());
 ESPDash.updateNumberCard("num1", random(0, 5000));
    ESPDash.updateTemperatureCard("temp1", random(0, 50));
    ESPDash.updateHumidityCard("hum1", random(0, 100));
    delay(3000);
}
void sendMessage(String outgoing) {
  LoRa.beginPacket();                   // start packet
  LoRa.write(destination);              // add destination address
  LoRa.write(localAddress);             // add sender address
  LoRa.write(msgCount);                 // add message ID
  LoRa.write(outgoing.length());        // add payload length
  LoRa.print(outgoing);                 // add payload
  LoRa.endPacket();                     // finish packet and send it
  msgCount++;                           // increment message ID
}

void onReceive(int packetSize) {
  if (packetSize == 0) return;          // if there's no packet, return

  // read packet header bytes:
  int recipient = LoRa.read();          // recipient address
  byte sender = LoRa.read();            // sender address
  byte incomingMsgId = LoRa.read();     // incoming msg ID
  byte incomingLength = LoRa.read();    // incoming msg length

  String incoming = "";

  while (LoRa.available()) {
    incoming += (char)LoRa.read();
  }

  if (incomingLength != incoming.length()) {   // check length for error
    Serial.println("error: message length does not match length");
    return;                             // skip rest of function
  }

  // if the recipient isn't this device or broadcast,
  if (recipient != localAddress && recipient != 0xFF) {
    Serial.println("This message is not for me.");
    return;                             // skip rest of function
  }

  // if message is for this device, or broadcast, print details:
  Serial.println("Received from: 0x" + String(sender, HEX));
  Serial.println("Sent to: 0x" + String(recipient, HEX));
  Serial.println("Message ID: " + String(incomingMsgId));
  Serial.println("Message length: " + String(incomingLength));
  Serial.println("Message: " + incoming);
  Serial.println("RSSI: " + String(LoRa.packetRssi()));
  Serial.println("Snr: " + String(LoRa.packetSnr()));
  Serial.println();
}

error is




LoRaDuplex:75:24: error: 'sendMessage' was not declared in this scope

     sendMessage(message);

                        ^

LoRaDuplex:82:31: error: 'onReceive' was not declared in this scope

   onReceive(LoRa.parsePacket());

                               ^

Multiple libraries were found for "WiFi.h"
 Used: C:\Users\haluk\Documents\Arduino\libraries\WiFi
 Not used: C:\Program
 Not used: C:\Users\haluk\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\WiFi
Multiple libraries were found for "AsyncTCP.h"
 Used: C:\Users\haluk\Documents\Arduino\libraries\AsyncTCP-master
Multiple libraries were found for "ESPAsyncWebServer.h"
 Used: C:\Users\haluk\Documents\Arduino\libraries\ESPAsyncWebServer-master
Multiple libraries were found for "FS.h"
 Used: C:\Users\haluk\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\FS
Multiple libraries were found for "ESPDash.h"
 Used: C:\Users\haluk\Documents\Arduino\libraries\ESP-DASH
Multiple libraries were found for "ArduinoJson.h"
 Used: C:\Users\haluk\Documents\Arduino\libraries\ArduinoJson-6.x
Multiple libraries were found for "SPI.h"
 Used: C:\Users\haluk\Documents\Arduino\libraries\SPI
 Not used: C:\Users\haluk\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\SPI
Multiple libraries were found for "LoRa.h"
 Used: C:\Users\haluk\Documents\Arduino\libraries\LoRa
 Not used: C:\Users\haluk\Documents\Arduino\libraries\arduino-LoRa-master
exit status 1
'sendMessage' was not declared in this scope

**Comment by ayushsharma82** [comment]
Please [Pastebin](https://pastebin.com) etc. for providing your sample. Pasting it directly in Github messes the formatting.

**Comment by halukmy** [comment]
@ayushsharma82  sorry it not works in turkey

anyway

when i try to use with https://github.com/sandeepmistry/arduino-LoRa  this lib, 

i got problem on sendmessage();

if i disable yours lib,

i can send message

**Comment by ayushsharma82** [comment]
It may be facing some problem with ESPAsyncWebserver dependency. Did your code use any interrupt?

**Comment by ayushsharma82** [comment]
Stale Issue
