### ISSUE TITLE
Linechart object update -- random reboot

### ISSUE THREAD

**Issue by green2blue** [ayushsharma82/ESP-DASH#52]
Hi, first thank you for your awesome work!

i use the linechart object to display the 24h (every 1h) the temperature of 3 different DS18B20 sensors.
I use 3 linechart objects and update them every 1h to get the temperature of the last 24h.
But i recognized that every day the ESP32 reboots randomly after the linechartupdate.  There is no special error but i am pretty sure that this is an problem with the library. Because after i removed the linechart object the random reboots are gone.Could you please check this?
If you want i can post my code here.

Thank you very much.

**Comment by ayushsharma82** [comment]
We are working on V3 with optimized code. Please wait for it's release.

**Comment by ayushsharma82** [comment]
@green2blue  V3 Released. Code has been refactored, therefore you might want to try it with this one. It will be a lot better!
