### ISSUE TITLE
LineChart enhancements

### ISSUE THREAD

**Issue by C-IT-AS** [ayushsharma82/ESP-DASH#53]
Hi,

I am planning to display a graph showing water temperature readings for the last 48 hours with 15 minute between samples.
Is there a way to:
* Control the "physical size" of the LineChart on the screen; i.e make it fill the whole available screen size?
* Lock y-axis size 0 - 100?
* Make y-axis ticks  0 / 10....90/100 (degrees Celsius)?
* Make the LineChart accept 4*24*2 = 192 datapoints? (= datapoint every 15 minutes for 2 days)

**Comment by ayushsharma82** [comment]
@C-IT-AS  You might want to try our V3 Release. It has an all-new bar chart with enhanced data handling. Thanks! Let us know if it lacks something.
