### ISSUE TITLE
Esp32 rebooting after receiving connection 

### ISSUE THREAD

**Issue by elC0mpa** [ayushsharma82/ESP-DASH#56]
Hello, first of all, I would like to thank you because of this library, i have been using it a lot and i think it is really usefull.
I am having a problem and i would like to know if it is because of your library. I am interfacing ten peripherals to esp 32 through external interrupts, and each time that certain amount of interrupts ellapsed, i update the Web view by using NumberCard. The problem is that the esp32 is being restarted and the serial monitor prints this message :
Guru Meditation Error: Core  1 panic'ed (Coprocessor exception)
Core 1 register dump:
PC      : 0x4015498f  PS      : 0x00060031  A0      : 0x800d2380  A1      : 0x3ffbe690
A2      : 0x3ffc10c4  A3      : 0x00000001  A4      : 0x00000000  A5      : 0x00000000
A6      : 0x00000003  A7      : 0x00060023  A8      : 0x00060021  A9      : 0x40092d94
A10     : 0x0000002a  A11     : 0x3ffd6bc0  A12     : 0x800f3f72  A13     : 0x3ffd6bb0
A14     : 0x3f400020  A15     : 0x00000000  SAR     : 0x0000001e  EXCCAUSE: 0x00000004
EXCVADDR: 0x00000000  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0x00000000
Core 1 was running in ISR context:
EPC1    : 0x4015498f  EPC2    : 0x00000000  EPC3    : 0x00000000  EPC4    : 0x40086a29

Backtrace: 0x4015498f:0x3ffbe690 0x400d237d:0x3ffbe770 0x400d1882:0x3ffbe790 0x40080f7d:0x3ffbe7b0 0x40084771:0x3ffbe7d0 0x4014858c:0x3ffd6a10 0x40148fc6:0x3ffd6b70 0x400f4306:0x3ffd6b90 0x400f3df5:0x3ffd6bb0 0x400f3f6f:0x3ffd6be0 0x400f4167:0x3ffd6c10 0x400f42b9:0x3ffd6c60 0x400e606a:0x3ffd6c80 0x400e612a:0x3ffd6db0 0x400e486d:0x3ffd6e50 0x400e5971:0x3ffd6f40 0x40154d6b:0x3ffd7210 0x401561d2:0x3ffd7230 0x40147d91:0x3ffd7280 0x40147dad:0x3ffd72c0 0x40145c41:0x3ffd72e0 0x40145cbd:0x3ffd7320 0x40146366:0x3ffd7340 0x40088b7d:0x3ffd7370

Rebooting...
I hope you could help me. Thanks in avance

**Comment by polaco1782** [comment]
Can you share your code? Seems like a math co-processor exception.

**Comment by elC0mpa** [comment]
Thanks for your answer @polaco1782. I am using ESP-DASH V2. But i realized that the problem was not related to the library, but to the external interrupts. This is because i stopped using them and started polling the peripherals and the problem was solved. The thing is that i have no idea why is this happening. I have been programming microcontrollers since long time ago and this had not happened to me before. I would appreciate any kind of help. Thank you

**Comment by polaco1782** [comment]
> Thanks for your answer @polaco1782. I am using ESP-DASH V2. But i realized that the problem was not related to the library, but to the external interrupts. This is because i stopped using them and started polling the peripherals and the problem was solved. The thing is that i have no idea why is this happening. I have been programming microcontrollers since long time ago and this had not happened to me before. I would appreciate any kind of help. Thank you

Interesting. It might be related to the libraries used in dash. There is no interrupt handling in dash code AFAIK.

**Comment by ayushsharma82** [comment]
I think this is related to AsyncWebServer which can cause conflicts with timer interrupts ( as it uses one itself for webserver tasks; instead of main loop ).

**Comment by ayushsharma82** [comment]
Stale. Let us know if this happens with V3. It's a lot stable. Thanks!
