### ISSUE TITLE
Slider change handler not executing with multiple sliders

### ISSUE THREAD

**Issue by hewittwill** [ayushsharma82/ESP-DASH#57]
After adding multiple slider cards, it appears that the slider handler does not fire. 

It appears I am not the only one to identify this issue: [link](https://www.reddit.com/r/esp32/comments/dn4wbr/espdash_multiple_slider/)

```
void sliderChanged(const char* id, int value) {
  Serial.println(String(id));
}

void setup() {

  ESPDash.attachSliderChanged(sliderChanged);

  ESPDash.addSliderCard("0", "Blue Channel", 2);
  ESPDash.addSliderCard("1", "White Channel", 2);
  ESPDash.addSliderCard("2", "Violet Channel", 2);

}

```

Not my entire sketch as it would be too big to see the salient issues, but the relevant lines included.

**Comment by polaco1782** [comment]
Hi,

We are currently rewriting dash to V3. (dash-next branch) It adds new features and corrects a lot of old problems. Can you check it out and see if it works?

Note that V3 works in a different way than V2, the card ID are now treated as integers.

**Comment by syntaxking** [comment]
Hi,

I tried sliders in the dash-next branch. However, there is no callback registration function for the slider's change event as in V2 (attachSliderChanged). How can I evaluate the changed slider values?

**Comment by polaco1782** [comment]
> Hi,
> 
> I tried sliders in the dash-next branch. However, there is no callback registration function for the slider's change event as in V2 (attachSliderChanged). How can I evaluate the changed slider values?

Hi

You call UpdateCard once, after creating it. Just attach function which will be called.

ESPDashV3::UpdateCard(const int cardID, void (*funptr)(CardData *))

See if that works. I'm still working on it, there is still some issues and documentation left to do.

**Comment by syntaxking** [comment]
Thanks, it's working! Great project!

**Comment by polaco1782** [comment]
> Thanks, it's working! Great project!

Nice, thanks for the feedback.
