### ISSUE TITLE
Error compiling for board ESP32 Dev Module.

### ISSUE THREAD

**Issue by Popov77** [ayushsharma82/ESP-DASH#58]
Compiling ESP32_slider sketch generates the following errors. 
What am I doing wrong? 

`
Arduino:1.8.10 (Windows 10), TD: 1.48, Kort:"ESP32 Dev Module, Disabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 921600, None"

Multiple libraries were found for "FS.h"
 Använd: C:\Users\dksoepv\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\FS
Multiple libraries were found for "ESPDash.h"
 Använd: C:\Users\dksoepv\OneDrive
Multiple libraries were found for "WiFi.h"
 Använd: C:\Users\dksoepv\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\WiFi
Oanvänd: C:\Users\dksoepv\OneDrive
Multiple libraries were found for "AsyncTCP.h"
In file included from C:\Users\dksoepv\AppData\Local\Temp\arduino_modified_sketch_360742\sketch_jan27b.ino:25:0:

 Använd: C:\Users\dksoepv\OneDrive
C:\Users\dksoepv\OneDrive - Alfa Laval\Documents\My Library\111\Arduino\Arduino-1.8.10\libraries\ESP-DASH-master\src/ESPDash.h:40:29: fatal error: ArduinoJson.h: No such file or directory

Multiple libraries were found for "ESPAsyncWebServer.h"
compilation terminated.

 Använd: C:\Users\dksoepv\OneDrive
exit status 1
Error compiling for board ESP32 Dev Module.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

`

**Comment by polaco1782** [comment]
Hi
Seems like you're missing a dependency:

> fatal error: ArduinoJson.h: No such file or directory

**Comment by Popov77** [comment]
Thanks, that was the reason!
Solved!
