### ISSUE TITLE
Hosting the dashboard on AWS

### ISSUE THREAD

**Issue by jamesthesken** [ayushsharma82/ESP-DASH#59]
Hey @ayushsharma82 I would like to use the dashboard for my project, [The Automated Farmer](https://github.com/jamesthesken/automatedfarmer). One of the goals is to host my front-end on AWS, which I already have my ESP8266 logging data to and a [simple web-page](https://theautomatedfarmer.com/?p=201) to view. 

I've been looking through the `vue-frontend` directory but am inexperienced in Vue.js. Do you have any tips for adding cards, graphs, etc. to the development webpage? I can work the incoming data from AWS but I am stuck understanding how to add new components to the dashboard without an ESP.

In exchange I can at least contribute to some documentation for bringing the project into the cloud. Thank you for the really great library, you make the ESP a lot more fun to work with.

**Comment by JoeBarouneD** [comment]
Did you read [the wiki](https://github.com/ayushsharma82/ESP-DASH/wiki/Building-Sketch) ?

**Comment by jamesthesken** [comment]
I did and have used the library on my ESP already, I'm referencing the `vue-frontend` [directory](https://github.com/ayushsharma82/ESP-DASH/tree/master/vue-frontend).

Where after I run:
```
npm run serve
```
How can components be added to the homepage? I would just like to use the frontend if possible, without the ESP in-the-loop. This might be good documentation to add regardless for anyone wanting to help develop the frontend. Thank you.

**Comment by JoeBarouneD** [comment]
Sorry, so you want to develop other "cards", i'm not experimented in js at all.

Good luck !

**Comment by ayushsharma82** [comment]
> I did and have used the library on my ESP already, I'm referencing the `vue-frontend` [directory](https://github.com/ayushsharma82/ESP-DASH/tree/master/vue-frontend).
> 
> Where after I run:
> 
> ```
> npm run serve
> ```
> 
> How can components be added to the homepage? I would just like to use the frontend if possible, without the ESP in-the-loop. This might be good documentation to add regardless for anyone wanting to help develop the frontend. Thank you.

Hi,
Sorry to disappoint, but ESP-DASH was never intended to be used with AWS. It follows a different architecture specifically made to work with esp8266. 

You will be looking at making a custom API server just like the Asyncwebserver code in the library and emulate the JSON responses for it.

I would personally start this from scratch if i wanted to achive that. 

Best of luck for your project!

**Comment by jamesthesken** [comment]
@ayushsharma82 All good!

Guess it's time to learn Vue! Thanks for your reply, I appreciate it.
