### ISSUE TITLE
data directory

### ISSUE THREAD

**Issue by windynips** [ayushsharma82/ESP-DASH#61]
So, what happened? i missed a ton, got a new job and i haven't been tinkering as much.

How can i change the Roll over wifi settings
How can i change the img directory, i liked my old logo....

good to see the updates!

**Comment by ayushsharma82** [comment]
Moved webpage from SPIFFS to MCU's program memory. There are a lot of updates which can't be listed in one go, you can go through the source code and see them for yourself. Thanks!
