### ISSUE TITLE
Possiblity of adding ElegantOTA as a card in ESP-DASH ?

### ISSUE THREAD

**Issue by RutvijP** [ayushsharma82/ESP-DASH#63]
Hi , 

Been working on ESP-DASH for a couple of weeks , if was wondering if ElegantOTA can be made as a card in the ESP-DASH library?

**Comment by ayushsharma82** [comment]
Possible but not intended.

Currently, all maintainers of ESP-DASH are busy with their personal lives, I'll leave this to open source community. Source code of both frontend and backend is available in the repository.

Regards,
Ayush
