### ISSUE TITLE
action attachments on ver3?

### ISSUE THREAD

**Issue by dbartelmus** [ayushsharma82/ESP-DASH#64]
Is there an alternative for
`ESPDash.attachButtonClick(buttonClicked);`
or
`ESPDash.attachSliderChanged(sliderChanged);`
 in this version already? I could not find it in source.

Maybe another way to handle such events?

**Comment by polaco1782** [comment]
On dash-next branch:

You call UpdateCard once, after creating it. Just attach function which will be called.

ESPDashV3::UpdateCard(const int cardID, void (*funptr)(CardData *))

**Comment by ayushsharma82** [comment]
To further clarify:

We can use a c++ lamba function like this.

```
ESPDash.UpdateCard("btnID1", [&](){
  // Handle this specific button trigger here
  digitalWrite(pin1, HIGH);
});
```

**Comment by ayushsharma82** [comment]
Please keep in mind that, syntax of dash-next branch can change anytime without notice. Better to use V2 for stable builds.

**Comment by dbartelmus** [comment]
Thanks for answers I will continue on beta, I like live on the edge 🤣

**Comment by dbartelmus** [comment]
> To further clarify: We can use a c++ lamba function like this. ``` ESPDash.UpdateCard("btnID1", [&](){ // Handle this specific button trigger here digitalWrite(pin1, HIGH); }); ```
> […](#)

no known conversion for argument 2 from 'setup()::__lambda1' to 'void (*)(CardData*)'
exit status 1
call of overloaded 'UpdateCard(const char [8], setup()::__lambda1)' is ambiguous

**Comment by ayushsharma82** [comment]
@polaco1782  will be checking it in a few days. He says that it should work. We'll wait for his answer.

**Comment by ayushsharma82** [comment]
Fixed with V3 Major. 

Callbacks are showcased in [Interactive Example](https://github.com/ayushsharma82/ESP-DASH/blob/master/examples/Interactive/Interactive.ino).
