### ISSUE TITLE
Compiler Error while building basic Demo 

### ISSUE THREAD

**Issue by jukno** [ayushsharma82/ESP-DASH#67]
Arduino: 1.8.12 (Mac OS X), Board: "OLIMEX ESP32-EVB, 80MHz, 115200, Default"

In file included from /Users/kse/devel/Projekte/ESP32/libraries/ArduinoJson/src/ArduinoJson/Variant/VariantContent.hpp:11:0,
                 from /Users/kse/devel/Projekte/ESP32/libraries/ArduinoJson/src/ArduinoJson/Variant/VariantSlot.hpp:9,
                 from /Users/kse/devel/Projekte/ESP32/libraries/ArduinoJson/src/ArduinoJson/Memory/MemoryPool.hpp:11,
                 from /Users/kse/devel/Projekte/ESP32/libraries/ArduinoJson/src/ArduinoJson/Strings/RamStringAdapter.hpp:7,
                 from /Users/kse/devel/Projekte/ESP32/libraries/ArduinoJson/src/ArduinoJson/Strings/StringAdapters.hpp:8,
                 from /Users/kse/devel/Projekte/ESP32/libraries/ArduinoJson/src/ArduinoJson/Misc/SerializedValue.hpp:7,
                 from /Users/kse/devel/Projekte/ESP32/libraries/ArduinoJson/src/ArduinoJson/Variant/VariantData.hpp:7,
                 from /Users/kse/devel/Projekte/ESP32/libraries/ArduinoJson/src/ArduinoJson/Variant/SlotFunctions.hpp:8,
                 from /Users/kse/devel/Projekte/ESP32/libraries/ArduinoJson/src/ArduinoJson/Array/ArrayIterator.hpp:7,
                 from /Users/kse/devel/Projekte/ESP32/libraries/ArduinoJson/src/ArduinoJson/Array/ArrayRef.hpp:8,
                 from /Users/kse/devel/Projekte/ESP32/libraries/ArduinoJson/src/ArduinoJson.hpp:17,
                 from /Users/kse/devel/Projekte/ESP32/libraries/ArduinoJson/src/ArduinoJson.h:9,
                 from /Users/kse/devel/Projekte/ESP32/libraries/ESP-DASH/src/ESPDash.h:40,
                 from /Users/kse/devel/Projekte/ESP32/libraries/ESP-DASH/src/ESPDash.cpp:1:
/Users/kse/devel/Projekte/ESP32/libraries/ArduinoJson/src/ArduinoJson/Variant/VariantFunctions.hpp: In instantiation of 'bool ArduinoJson6152_0000010::variantSetInteger(ArduinoJson6152_0000010::VariantData*, T) [with T = long long unsigned int]':
/Users/kse/devel/Projekte/ESP32/libraries/ArduinoJson/src/ArduinoJson/Variant/VariantRef.hpp:187:32:   required from 'bool ArduinoJson6152_0000010::VariantRef::set(T, typename ArduinoJson6152_0000010::enable_if<ArduinoJson6152_0000010::is_integral<T>::value>::type*) const [with T = long long unsigned int; typename ArduinoJson6152_0000010::enable_if<ArduinoJson6152_0000010::is_integral<T>::value>::type = void]'
/Users/kse/devel/Projekte/ESP32/libraries/ArduinoJson/src/ArduinoJson/Object/MemberProxy.hpp:44:5:   required from 'typename ArduinoJson6152_0000010::enable_if<(! ArduinoJson6152_0000010::is_array<TValue>::value), ArduinoJson6152_0000010::MemberProxy<TParent, TStringRef>&>::type ArduinoJson6152_0000010::MemberProxy<TParent, TStringRef>::operator=(const TValue&) [with TValue = long long unsigned int; TObject = ArduinoJson6152_0000010::ObjectRef; TStringRef = const char*; typename ArduinoJson6152_0000010::enable_if<(! ArduinoJson6152_0000010::is_array<TValue>::value), ArduinoJson6152_0000010::MemberProxy<TParent, TStringRef>&>::type = ArduinoJson6152_0000010::MemberProxy<ArduinoJson6152_0000010::ObjectRef, const char*>&]'
/Users/kse/devel/Projekte/ESP32/libraries/ESP-DASH/src/ESPDash.cpp:917:29:   required from here
/Users/kse/devel/Projekte/ESP32/libraries/ArduinoJson/src/ArduinoJson/Variant/VariantFunctions.hpp:135:3: error: static assertion failed: To use 64-bit integers with ArduinoJson, you must set ARDUINOJSON_USE_LONG_LONG to 1. See https://arduinojson.org/v6/api/config/use_long_long/
   ARDUINOJSON_ASSERT_INTEGER_TYPE_IS_SUPPORTED(T);
   ^
Mehrere Bibliotheken wurden für "WiFi.h" gefunden
 Benutzt: /Users/kse/Library/Arduino15/packages/esp32/hardware/esp32/1.0.4/libraries/WiFi
 Nicht benutzt: /private/var/folders/4t/4m1hm0s922n8r2xzkcnlcmkm0000gn/T/AppTranslocation/7F191B8C-B1C7-4CA6-8643-30C49A6F70CA/d/Arduino.app/Contents/Java/libraries/WiFi
exit status 1
Fehler beim Kompilieren für das Board OLIMEX ESP32-EVB.

**Comment by ayushsharma82** [comment]
Should be fixed with v2.2.5 minor release. Let us know if the issue still persists.
