### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by danbicks** [ayushsharma82/ESP-DASH#68]
Hi, just stumbled on this amazing work. Reminds me of when I first used Online Web dashboards for IOT. Great idea to have a small implementation running on the device itself. Could we add if not already in the feature list a pop up alert box? back color and text with option. Can  it also trigger a small wave file? sound. Would be awesome for alarm notification etc. 
Have you a night background theme? tablet running connection beside bed would need to be much dimmer. Need to sleep Lol.
Amazing work guys, really looking forward to trying this version 3 out.
Dans

**Comment by ayushsharma82** [comment]
Yup. I'll add server pushed toasts to our to-do list. We'll develop it once we are ready to roll with V3.

Thanks

**Comment by 2black0** [comment]
it will be great if we can add String, Date, Time format in a card
for button I think toggle button is important too

**Comment by ayushsharma82** [comment]
@2black0  Toggle Button and String ( Generic ) Card has been added with V3 ( #92 ) . It will be released in a couple of days after review. Thanks!
