### ISSUE TITLE
How can I change the images of webserver?

### ISSUE THREAD

**Issue by JeanAguiar** [ayushsharma82/ESP-DASH#7]
I tried to change the png images on data/img folder, and then run SPIFFS again, but don't worked. Can you help me? I tried to translate the webpage too, rewriting the html file, but don't worked too

**Comment by ayushsharma82** [comment]
Images are stored in cache after first load so, Ctrl+Shift+R to reload page with new images.

**Comment by JeanAguiar** [comment]
Thanks!
