### ISSUE TITLE
using analogRead() breaks functionality

### ISSUE THREAD

**Issue by Moosdijk** [ayushsharma82/ESP-DASH#71]
Hi all,

Using ESP8266_basic.ino from the examples, if I add an analogRead() to the loop() function, the dashboard is not accessible anymore.
It still updates the cards, but the sketch is broken.

I've tested this on multiple wemos D1 mini v 3.0.0

**Comment by ayushsharma82** [comment]
That must be related to the ESPAsyncWebserver dependency. Do you have any interrupt attached?

**Comment by ayushsharma82** [comment]
Stale
