### ISSUE TITLE
[dash-next] information leak to github

### ISSUE THREAD

**Issue by Rotzbua** [ayushsharma82/ESP-DASH#72]
Not a big think, but may consider.

## Observation

Page `contribute` requests information about repository from github.

It is a cross request. Every crossrequest contain an `origin` header. The header contains the local network address.

## Risk

Leaks local network information to github.

## Possible solution

It is not possible to disable `origin` header.

1. Option:
Add a button "request information from github". --> User makes an active decision to connect.

2. Option:
Make option in backend to disable request.

3. Option:
Remove function.

4. Option:
Proxy request over ESP. Ugly, not recommended.

**Comment by polaco1782** [comment]
@ayushsharma82 What you think about this?

**Comment by ayushsharma82** [comment]
@polaco1782  I think it's not much of a concern, knowing GitHub is a trusted entity.

**Comment by ayushsharma82** [comment]
Removed Github integration in UI revamp.
