### ISSUE TITLE
[Feature] Use ENUM instead of integer for status card

### ISSUE THREAD

**Issue by bastiengrignon** [ayushsharma82/ESP-DASH#76]
It could be nice to use name instead of just a number for `statusCard`.

Like `StatusCard::WARNING`, or `STATUS_WARNING`, `STATUS_OK`, ... (I don't know which typo would be good)

I think it's more user-friendly, and help the user to avoid knowing which number correspond to status type.

**Comment by polaco1782** [comment]
That is already implemented with dash-v3 branch.

https://github.com/ayushsharma82/ESP-DASH/blob/dash-next/src/ESPDash.cpp

**Comment by bastiengrignon** [comment]
Ok great ! I will close this issue
