### ISSUE TITLE
List and graphs

### ISSUE THREAD

**Issue by JeanAguiar** [ayushsharma82/ESP-DASH#8]
Hello,
This library is just perfect, and I would like to give a hint ... How about using some buttons to change the state of ports, something like `EspDash.addButton ("Button", State)`
and lists / graphs, with the data coming to X tab, is perfect, thank you from now on.
Taking advantage of the topic, how can I modify the HTML, css and javascript in the front end part to improve the look without compromising the library's operation?

**Comment by ayushsharma82** [comment]
I have included the index.html and css file in spiffs folder, You can modify it and zip it to .gzip with Winzip.

**Comment by ayushsharma82** [comment]
and i will try to add a line graph if it fits the size and does not disrupt the 1s loading time.

**Comment by JeanAguiar** [comment]
Thank you!!!!! Your library is amazing!

**Comment by ayushsharma82** [comment]
Added Line Chart with ESP-DASH V2 Release! Thanks for the suggestions! 😊🎉

**Comment by JeanAguiar** [comment]
Your lib is amazing! Thanks for the update!
