### ISSUE TITLE
Sending float number 

### ISSUE THREAD

**Issue by KalifiaBillal** [ayushsharma82/ESP-DASH#85]
Hello , I was wondering How may i send  float number instead of an int

**Comment by induchoy** [comment]
> Hello , I was wondering How may i send float number instead of an int

dear have you solve this problem? i am facing same problem. please help me if possible.

**Comment by ayushsharma82** [comment]
Support for `float` has been added in V3-beta.

**Comment by induchoy** [comment]
> Support for `float` has been added in V3-beta.

Thanks for your reply. Where i can find V3-beta firmware??  Is it available for testing ?

**Comment by ayushsharma82** [comment]
@induchoy  You can check out our `dash-next` branch. There is no documentation right now. You can see ESP32 / ESP8266 basic examples to get a bit of info on how the V3 works.

**_Please know that if you are going to use it in your project, the syntax might change before the final release._**

**Comment by ayushsharma82** [comment]
Added in V3 ( Currently up for review ). #92 🎉
