### ISSUE TITLE
Arduino Json V6.x.x.x

### ISSUE THREAD

**Issue by IanWalker** [ayushsharma82/ESP-DASH#9]
Hi There

Thanks for a fantastic library.
It does not work with the current Arduino  Json release. 
Reverted to 5.12 and all OK

**Comment by ayushsharma82** [comment]
Thanks for the reporting the issue. i will fix it within 4-5 days.

**Comment by ayushsharma82** [comment]
Just checked out that ArduinoJSON v6 is still in beta Stage. They are saying that functions etc. will change in v6 with revisions.. So, I will update ESP-DASH Dependency when it comes out of beta release.

**Comment by ayushsharma82** [comment]
Updated to ArduinoJson V6.7.0 with ESP-DASH V2. 🎉
