### ISSUE TITLE
Order of cards?

### ISSUE THREAD

**Issue by oldjiberjaber** [ayushsharma82/ESP-DASH#90]
There seems to be no logic to the order of the cards presented on the dashboard?  Whilst they will be presented in a consistent format, they don't follow either the order in Setup or the update order in loop?
Shouldn't it be possible to programme the order of the cards?

eg If I define and update the following cards in Setup():
ESPDash.addNumberCard("IPV", "Input Voltage", 0);
    ESPDash.addTemperatureCard("temp1", "Garden Temperature", 0, 1);
    ESPDash.addHumidityCard("hum1", "Garden Humidity", 2);
    ESPDash.addTemperatureCard("DewP", "Dew Point", 0, 3);
    ESPDash.addTemperatureCard("DStemp0", "Dew Strap 0", 0, 4);
    ESPDash.addTemperatureCard("DStemp1", "Dew Strap 1", 0, 5);
    ESPDash.addHumidityCard("DSpwr0", "DewStrap 0 Power", 6);
    ESPDash.addHumidityCard("DSpwr1", "DewStrap 1 Power", 7);

And in the loop():
ESPDash.updateNumberCard("IPV", random(12, 14));
    ESPDash.updateTemperatureCard("temp1", (int) TempC );
    ESPDash.updateHumidityCard("hum1",  (int) Humidity );
    ESPDash.updateTemperatureCard("DewP",  (int) DP );
    ESPDash.updateTemperatureCard("DStemp0",  random(2, 22) );    
    ESPDash.updateTemperatureCard("DStemp0",  random(4, 24));
    ESPDash.updateHumidityCard("DSpwr0",  random(0, 100) );
    ESPDash.updateHumidityCard("DSpwr1",  random(0, 100) );

But the display is as follows:

![image](https://user-images.githubusercontent.com/38729733/96326256-f4651900-1026-11eb-9740-6bb62f1786e5.png)

**Comment by ayushsharma82** [comment]
Currently, it's not possible. The webpage adds all the cards one by one. I'll try adding `index` attribute in V3 if I get some time.

**Comment by ayushsharma82** [comment]
Added this feature in [ESP-DASH **Pro**](https://espdash.pro) with couple of new cards and charts.
