### ISSUE TITLE
Serial debug output disable?

### ISSUE THREAD

**Issue by oldjiberjaber** [ayushsharma82/ESP-DASH#91]
There appears to be no way to turn off the serial output debug messages from Dash? (without hacking the library I guess?)

My application is acting as a dashboard and interface to a legacy system over serial, I could do without the debug messages on the serial port after I've debugged my code :) 

Might be worth considering a debug level?

eg  https://github.com/khoih-prog/ESPAsync_WiFiManager

> // Use from 0 to 4. Higher number, more debugging messages and memory usage.
> #define _ESPASYNC_WIFIMGR_LOGLEVEL_    3

**Comment by oldjiberjaber** [comment]
Changing line 48 of ESPDash.h from 1 to 0 makes no difference - is it supposed to?

#define DEBUG_MODE 0 // change to 1 for DEBUG Messages

However, commenting out the serial.print part of line 5 of ESPDash.cpp does stop the printing to the serial port.
change 
#define debugPrintln(...) Serial.println(__VA_ARGS__)
to
#define debugPrintln(...) // Serial.println(__VA_ARGS__)

**Comment by oldjiberjaber** [comment]
Commenting out line 48 of ESPDash.h disables debug output.
eg:
 // #define DEBUG_MODE 0 // change to 1 for DEBUG Messages

**Comment by polaco1782** [comment]
Please, checkout dash-next branch, if you want to add or suggest any feature.

**Comment by ayushsharma82** [comment]
As we progress towards the V3 release, I've taken note of this issue and debug messages will be off by default. Thanks!
