### ISSUE TITLE
Included Javascript

### ISSUE THREAD

**Issue by cotestatnt** [ayushsharma82/ESP-DASH#94]
Leave the choice to the user whether to load the javascript locally or from a remote CDN server.
Or at least, include code only when needed: if I don't use charts, why should I include the code for the chartJS on my webpage?

**Comment by ayushsharma82** [comment]
The whole point of ESP-DASH is to work even without an internet connection. I can't prioritize one's problem over accessibility for everybody else. You are free to edit the Vuejs source code included in the repo and remove chartJS dependency.

**Comment by cotestatnt** [comment]
> The whole point of ESP-DASH is to work even without an internet connection. I can't prioritize one's problem over accessibility for everybody else. You are free to edit the Vuejs source code included in the repo and remove chartJS dependency.

Mine would be just a suggestion, not a problem. 
Load hundreds of bytes which will not be used later, is a waste of time and resources, but i can undertstand is not so easy improve flexibility for everyone's need.

Anyway, thanks for your very useful library.
