### ISSUE TITLE
date & time card

### ISSUE THREAD

**Issue by 2black0** [ayushsharma82/ESP-DASH#95]
it will be great if esp-dash support date & time card with general format like hh:mm:ss and dd/mm/yyyy

yeah we know general card can be used to show String datatype but idk when I use general card and String datatype, web cannot load normally

**Comment by ayushsharma82** [comment]
Yeah there's a problem with `String` type of Generic Card. I'm on to fixing it.

**Comment by ayushsharma82** [comment]
@2black0 Generic Card with String datatype has been fixed with v3.0.3 ( #105 ). Let me know if you still face that issue.
